// Code generated by gitmap db generate. DO NOT EDIT.

package pipelinedb

import (
	"github.com/alimtvnetwork/gitmap-v28/gitmap/dbengine"
)

// Canonical table name constants.
const (
	PipelineDbStatsTable = "PipelineDbStats"
	PipelineErrorRecordTable = "PipelineErrorRecord"
	PipelineErrorTable = PipelineErrorRecordTable
	PipelineRunRecordTable = "PipelineRunRecord"
	PipelineRunTable = PipelineRunRecordTable
	PipelineSplitDbTable = "PipelineSplitDb"
)

// Dedicated QueryBuilder type aliases.
type (
	// PipelineDbStatsQueryBuilder is the dedicated query builder for PipelineDbStats.
	PipelineDbStatsQueryBuilder = dbengine.QueryBuilder[PipelineDbStats, PipelineDbStatsFieldType]
	// PipelineErrorRecordQueryBuilder is the dedicated query builder for PipelineErrorRecord.
	PipelineErrorRecordQueryBuilder = dbengine.QueryBuilder[PipelineErrorRecord, PipelineErrorRecordFieldType]
	// PipelineErrorQueryBuilder is an alias to PipelineErrorRecordQueryBuilder for concise business usage.
	PipelineErrorQueryBuilder = PipelineErrorRecordQueryBuilder
	// PipelineRunRecordQueryBuilder is the dedicated query builder for PipelineRunRecord.
	PipelineRunRecordQueryBuilder = dbengine.QueryBuilder[PipelineRunRecord, PipelineRunRecordFieldType]
	// PipelineRunQueryBuilder is an alias to PipelineRunRecordQueryBuilder for concise business usage.
	PipelineRunQueryBuilder = PipelineRunRecordQueryBuilder
	// PipelineSplitDbQueryBuilder is the dedicated query builder for PipelineSplitDb.
	PipelineSplitDbQueryBuilder = dbengine.QueryBuilder[PipelineSplitDb, PipelineSplitDbFieldType]
)

// Dedicated generic Repository type aliases.
type (
	// PipelineDbStatsRepository is the dedicated generic repository for PipelineDbStats.
	PipelineDbStatsRepository = dbengine.Repository[PipelineDbStats, PipelineDbStatsFieldType]
	// PipelineErrorRecordRepository is the dedicated generic repository for PipelineErrorRecord.
	PipelineErrorRecordRepository = dbengine.Repository[PipelineErrorRecord, PipelineErrorRecordFieldType]
	// PipelineErrorRepository is an alias to PipelineErrorRecordRepository for concise business usage.
	PipelineErrorRepository = PipelineErrorRecordRepository
	// PipelineRunRecordRepository is the dedicated generic repository for PipelineRunRecord.
	PipelineRunRecordRepository = dbengine.Repository[PipelineRunRecord, PipelineRunRecordFieldType]
	// PipelineRunRepository is an alias to PipelineRunRecordRepository for concise business usage.
	PipelineRunRepository = PipelineRunRecordRepository
	// PipelineSplitDbRepository is the dedicated generic repository for PipelineSplitDb.
	PipelineSplitDbRepository = dbengine.Repository[PipelineSplitDb, PipelineSplitDbFieldType]
)

// Typed DbRepo aliases for concise business usage.
type (
	// PipelineErrorDbRepo is an alias to PipelineErrorRecordDbRepo for concise business usage.
	PipelineErrorDbRepo = PipelineErrorRecordDbRepo
	// PipelineRunDbRepo is an alias to PipelineRunRecordDbRepo for concise business usage.
	PipelineRunDbRepo = PipelineRunRecordDbRepo
)
