// Code generated by gitmap db generate. DO NOT EDIT.

package pipelinedb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/gitmap/pipelinedb/enums"
)

type PipelineErrorRecord struct {
	RunId        uint64 `json:"runId"`
	RepoSlug     string `json:"repoSlug"`
	WorkflowName string `json:"workflowName"`
	StepName     string `json:"stepName"`
	ErrorText    string `json:"errorText"`
	RawLogs      string `json:"rawLogs,omitempty"`
	Notes        string `json:"notes,omitempty"`
	Comments     string `json:"comments,omitempty"`
	CreatedAt    string `json:"createdAt"`
}

// ScanPipelineErrorRecord maps a database row scanner to a PipelineErrorRecord entity.
func ScanPipelineErrorRecord(row dbengine.RowScanner) (*PipelineErrorRecord, error) {
	var item PipelineErrorRecord
	var (
		raw_RunId        any
		raw_RepoSlug     any
		raw_WorkflowName any
		raw_StepName     any
		raw_ErrorText    any
		raw_RawLogs      any
		raw_Notes        any
		raw_Comments     any
		raw_CreatedAt    any
	)
	err := row.Scan(
		&raw_RunId,
		&raw_RepoSlug,
		&raw_WorkflowName,
		&raw_StepName,
		&raw_ErrorText,
		&raw_RawLogs,
		&raw_Notes,
		&raw_Comments,
		&raw_CreatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.RunId = dbengine.ScanUint64(raw_RunId)
	item.RepoSlug = dbengine.ScanString(raw_RepoSlug)
	item.WorkflowName = dbengine.ScanString(raw_WorkflowName)
	item.StepName = dbengine.ScanString(raw_StepName)
	item.ErrorText = dbengine.ScanString(raw_ErrorText)
	item.RawLogs = dbengine.ScanString(raw_RawLogs)
	item.Notes = dbengine.ScanString(raw_Notes)
	item.Comments = dbengine.ScanString(raw_Comments)
	item.CreatedAt = dbengine.ScanString(raw_CreatedAt)
	return &item, nil
}

// PipelineErrorRecordDbRepo provides typed database repository access for PipelineErrorRecord.
type PipelineErrorRecordDbRepo struct {
	db   *dbengine.DbWrapper
	repo *PipelineErrorRecordRepository
}

// NewPipelineErrorRecordDbRepo initializes a typed repository for PipelineErrorRecord.
func NewPipelineErrorRecordDbRepo(db *dbengine.DbWrapper) *PipelineErrorRecordDbRepo {
	repo := dbengine.NewRepository[PipelineErrorRecord, enums.PipelineErrorRecordFieldType](
		db,
		enums.PipelineErrorRecordTable,
		ScanPipelineErrorRecord,
	)
	return &PipelineErrorRecordDbRepo{
		db:   db,
		repo: repo,
	}
}

// NewPipelineErrorDbRepo is an alias constructor for PipelineErrorRecordDbRepo.
func NewPipelineErrorDbRepo(db *dbengine.DbWrapper) *PipelineErrorDbRepo {
	return NewPipelineErrorRecordDbRepo(db)
}

// Db returns the underlying DbWrapper.
func (r *PipelineErrorRecordDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *PipelineErrorRecordDbRepo) Repo() *PipelineErrorRecordRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *PipelineErrorRecordDbRepo) Query() *PipelineErrorRecordQueryBuilder {
	return r.repo.Query().Select(enums.PipelineErrorRecordDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *PipelineErrorRecordDbRepo) QueryBare() *PipelineErrorRecordQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *PipelineErrorRecordDbRepo) FindAll(ctx context.Context) dbengine.ListResult[PipelineErrorRecord] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *PipelineErrorRecordDbRepo) First(ctx context.Context) dbengine.EntityResult[PipelineErrorRecord] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *PipelineErrorRecordDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}
