// Code generated by gitmap db generate. DO NOT EDIT.

package pipelinedb

import "fmt"

// PipelineSplitDbFieldType represents column name enums for PipelineSplitDb.
type PipelineSplitDbFieldType string

// Name returns the identifier name of the field enum.
func (e PipelineSplitDbFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e PipelineSplitDbFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e PipelineSplitDbFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum, string, or fmt.Stringer.
func (e PipelineSplitDbFieldType) IsCompare(target any) bool {
	switch v := target.(type) {
	case PipelineSplitDbFieldType:
		return e == v
	case string:
		return string(e) == v
	case fmt.Stringer:
		return string(e) == v.String()
	default:
		return false
	}
}

type pipelineSplitDbDbRegistry struct {
	RepoSlug PipelineSplitDbFieldType
	Path PipelineSplitDbFieldType
}

// PipelineSplitDbDb provides scoped access to field enums: PipelineSplitDbDb.<Field>.
var PipelineSplitDbDb = pipelineSplitDbDbRegistry{
	RepoSlug: "RepoSlug",
	Path: "Path",
}

// PipelineSplitDbField is an alias to PipelineSplitDbDb.
var PipelineSplitDbField = PipelineSplitDbDb

// PipelineSplitDbTable represents the canonical table name.
const PipelineSplitDbTable = "PipelineSplitDb"

// PipelineRunRecordFieldType represents column name enums for PipelineRunRecord.
type PipelineRunRecordFieldType string

// Name returns the identifier name of the field enum.
func (e PipelineRunRecordFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e PipelineRunRecordFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e PipelineRunRecordFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum, string, or fmt.Stringer.
func (e PipelineRunRecordFieldType) IsCompare(target any) bool {
	switch v := target.(type) {
	case PipelineRunRecordFieldType:
		return e == v
	case string:
		return string(e) == v
	case fmt.Stringer:
		return string(e) == v.String()
	default:
		return false
	}
}

type pipelineRunRecordDbRegistry struct {
	RunId PipelineRunRecordFieldType
	RepoSlug PipelineRunRecordFieldType
	WorkflowName PipelineRunRecordFieldType
	Status PipelineRunRecordFieldType
	Conclusion PipelineRunRecordFieldType
	Branch PipelineRunRecordFieldType
	Sha PipelineRunRecordFieldType
	EtaSeconds PipelineRunRecordFieldType
	DurationSeconds PipelineRunRecordFieldType
	RunUrl PipelineRunRecordFieldType
	IsSuccess PipelineRunRecordFieldType
	Notes PipelineRunRecordFieldType
	Comments PipelineRunRecordFieldType
	CreatedAt PipelineRunRecordFieldType
	UpdatedAt PipelineRunRecordFieldType
}

// PipelineRunRecordDb provides scoped access to field enums: PipelineRunRecordDb.<Field>.
var PipelineRunRecordDb = pipelineRunRecordDbRegistry{
	RunId: "RunId",
	RepoSlug: "RepoSlug",
	WorkflowName: "WorkflowName",
	Status: "Status",
	Conclusion: "Conclusion",
	Branch: "Branch",
	Sha: "Sha",
	EtaSeconds: "EtaSeconds",
	DurationSeconds: "DurationSeconds",
	RunUrl: "RunUrl",
	IsSuccess: "IsSuccess",
	Notes: "Notes",
	Comments: "Comments",
	CreatedAt: "CreatedAt",
	UpdatedAt: "UpdatedAt",
}

// PipelineRunRecordField is an alias to PipelineRunRecordDb.
var PipelineRunRecordField = PipelineRunRecordDb

// PipelineRunRecordTable represents the canonical table name.
const PipelineRunRecordTable = "PipelineRunRecord"

// PipelineErrorRecordFieldType represents column name enums for PipelineErrorRecord.
type PipelineErrorRecordFieldType string

// Name returns the identifier name of the field enum.
func (e PipelineErrorRecordFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e PipelineErrorRecordFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e PipelineErrorRecordFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum, string, or fmt.Stringer.
func (e PipelineErrorRecordFieldType) IsCompare(target any) bool {
	switch v := target.(type) {
	case PipelineErrorRecordFieldType:
		return e == v
	case string:
		return string(e) == v
	case fmt.Stringer:
		return string(e) == v.String()
	default:
		return false
	}
}

type pipelineErrorRecordDbRegistry struct {
	RunId PipelineErrorRecordFieldType
	RepoSlug PipelineErrorRecordFieldType
	WorkflowName PipelineErrorRecordFieldType
	StepName PipelineErrorRecordFieldType
	ErrorText PipelineErrorRecordFieldType
	RawLogs PipelineErrorRecordFieldType
	Notes PipelineErrorRecordFieldType
	Comments PipelineErrorRecordFieldType
	CreatedAt PipelineErrorRecordFieldType
}

// PipelineErrorRecordDb provides scoped access to field enums: PipelineErrorRecordDb.<Field>.
var PipelineErrorRecordDb = pipelineErrorRecordDbRegistry{
	RunId: "RunId",
	RepoSlug: "RepoSlug",
	WorkflowName: "WorkflowName",
	StepName: "StepName",
	ErrorText: "ErrorText",
	RawLogs: "RawLogs",
	Notes: "Notes",
	Comments: "Comments",
	CreatedAt: "CreatedAt",
}

// PipelineErrorRecordField is an alias to PipelineErrorRecordDb.
var PipelineErrorRecordField = PipelineErrorRecordDb

// PipelineErrorRecordTable represents the canonical table name.
const PipelineErrorRecordTable = "PipelineErrorRecord"

// PipelineDbStatsFieldType represents column name enums for PipelineDbStats.
type PipelineDbStatsFieldType string

// Name returns the identifier name of the field enum.
func (e PipelineDbStatsFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e PipelineDbStatsFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e PipelineDbStatsFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum, string, or fmt.Stringer.
func (e PipelineDbStatsFieldType) IsCompare(target any) bool {
	switch v := target.(type) {
	case PipelineDbStatsFieldType:
		return e == v
	case string:
		return string(e) == v
	case fmt.Stringer:
		return string(e) == v.String()
	default:
		return false
	}
}

type pipelineDbStatsDbRegistry struct {
	Path PipelineDbStatsFieldType
	Size PipelineDbStatsFieldType
	TotalRuns PipelineDbStatsFieldType
	SuccessRuns PipelineDbStatsFieldType
	FailedRuns PipelineDbStatsFieldType
	ErrorLogCount PipelineDbStatsFieldType
	SegmentCount PipelineDbStatsFieldType
	LastUpdated PipelineDbStatsFieldType
}

// PipelineDbStatsDb provides scoped access to field enums: PipelineDbStatsDb.<Field>.
var PipelineDbStatsDb = pipelineDbStatsDbRegistry{
	Path: "Path",
	Size: "Size",
	TotalRuns: "TotalRuns",
	SuccessRuns: "SuccessRuns",
	FailedRuns: "FailedRuns",
	ErrorLogCount: "ErrorLogCount",
	SegmentCount: "SegmentCount",
	LastUpdated: "LastUpdated",
}

// PipelineDbStatsField is an alias to PipelineDbStatsDb.
var PipelineDbStatsField = PipelineDbStatsDb

// PipelineDbStatsTable represents the canonical table name.
const PipelineDbStatsTable = "PipelineDbStats"
