// Code generated by gitmap db generate. DO NOT EDIT.

package pipelinedb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/gitmap/pipelinedb/enums"
)

type PipelineRunRecord struct {
	RunId           uint64 `json:"runId"`
	RepoSlug        string `json:"repoSlug"`
	WorkflowName    string `json:"workflowName"`
	Status          string `json:"status"`
	Conclusion      string `json:"conclusion"`
	Branch          string `json:"branch"`
	Sha             string `json:"sha"`
	EtaSeconds      int    `json:"etaSeconds"`
	DurationSeconds int    `json:"durationSeconds"`
	RunUrl          string `json:"runUrl"`
	IsSuccess       bool   `json:"isSuccess"`
	Notes           string `json:"notes,omitempty"`
	Comments        string `json:"comments,omitempty"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

// ScanPipelineRunRecord maps a database row scanner to a PipelineRunRecord entity.
func ScanPipelineRunRecord(row dbengine.RowScanner) (*PipelineRunRecord, error) {
	var item PipelineRunRecord
	var (
		raw_RunId           any
		raw_RepoSlug        any
		raw_WorkflowName    any
		raw_Status          any
		raw_Conclusion      any
		raw_Branch          any
		raw_Sha             any
		raw_EtaSeconds      any
		raw_DurationSeconds any
		raw_RunUrl          any
		raw_IsSuccess       any
		raw_Notes           any
		raw_Comments        any
		raw_CreatedAt       any
		raw_UpdatedAt       any
	)
	err := row.Scan(
		&raw_RunId,
		&raw_RepoSlug,
		&raw_WorkflowName,
		&raw_Status,
		&raw_Conclusion,
		&raw_Branch,
		&raw_Sha,
		&raw_EtaSeconds,
		&raw_DurationSeconds,
		&raw_RunUrl,
		&raw_IsSuccess,
		&raw_Notes,
		&raw_Comments,
		&raw_CreatedAt,
		&raw_UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.RunId = dbengine.ScanUint64(raw_RunId)
	item.RepoSlug = dbengine.ScanString(raw_RepoSlug)
	item.WorkflowName = dbengine.ScanString(raw_WorkflowName)
	item.Status = dbengine.ScanString(raw_Status)
	item.Conclusion = dbengine.ScanString(raw_Conclusion)
	item.Branch = dbengine.ScanString(raw_Branch)
	item.Sha = dbengine.ScanString(raw_Sha)
	item.EtaSeconds = dbengine.ScanInt(raw_EtaSeconds)
	item.DurationSeconds = dbengine.ScanInt(raw_DurationSeconds)
	item.RunUrl = dbengine.ScanString(raw_RunUrl)
	item.IsSuccess = dbengine.ScanBool(raw_IsSuccess)
	item.Notes = dbengine.ScanString(raw_Notes)
	item.Comments = dbengine.ScanString(raw_Comments)
	item.CreatedAt = dbengine.ScanString(raw_CreatedAt)
	item.UpdatedAt = dbengine.ScanString(raw_UpdatedAt)
	return &item, nil
}

// PipelineRunRecordDbRepo provides typed database repository access for PipelineRunRecord.
type PipelineRunRecordDbRepo struct {
	db   *dbengine.DbWrapper
	repo *PipelineRunRecordRepository
}

// NewPipelineRunRecordDbRepo initializes a typed repository for PipelineRunRecord.
func NewPipelineRunRecordDbRepo(db *dbengine.DbWrapper) *PipelineRunRecordDbRepo {
	repo := dbengine.NewRepository[PipelineRunRecord, enums.PipelineRunRecordFieldType](
		db,
		enums.PipelineRunRecordTable,
		ScanPipelineRunRecord,
	)
	return &PipelineRunRecordDbRepo{
		db:   db,
		repo: repo,
	}
}

// NewPipelineRunDbRepo is an alias constructor for PipelineRunRecordDbRepo.
func NewPipelineRunDbRepo(db *dbengine.DbWrapper) *PipelineRunDbRepo {
	return NewPipelineRunRecordDbRepo(db)
}

// Db returns the underlying DbWrapper.
func (r *PipelineRunRecordDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *PipelineRunRecordDbRepo) Repo() *PipelineRunRecordRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *PipelineRunRecordDbRepo) Query() *PipelineRunRecordQueryBuilder {
	return r.repo.Query().Select(enums.PipelineRunRecordDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *PipelineRunRecordDbRepo) QueryBare() *PipelineRunRecordQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *PipelineRunRecordDbRepo) FindAll(ctx context.Context) dbengine.ListResult[PipelineRunRecord] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *PipelineRunRecordDbRepo) First(ctx context.Context) dbengine.EntityResult[PipelineRunRecord] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *PipelineRunRecordDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}
