<#
.SYNOPSIS
    Register cloned repositories with GitHub Desktop.
.DESCRIPTION
    Auto-generated by gitmap. Run this script after cloning
    to add all repositories to GitHub Desktop.
    Requires GitHub Desktop CLI (github) to be available in PATH.
#>

param(
    [string]$BaseDir = "."
)

# Check if GitHub Desktop CLI is available
$ghDesktop = Get-Command "github" -ErrorAction SilentlyContinue
if (-not $ghDesktop) {
    Write-Host ""
    Write-Host "  XX GitHub Desktop CLI not found." -ForegroundColor Red
    Write-Host "    Install GitHub Desktop and ensure 'github' is in your PATH." -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

Write-Host ""
Write-Host "  +======================================+" -ForegroundColor DarkCyan
Write-Host "  |     gitmap -- GitHub Desktop         |" -ForegroundColor DarkCyan
Write-Host "  +======================================+" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Registering 0 repositories..." -ForegroundColor Cyan
Write-Host ""

$succeeded = 0
$failed = 0

Write-Host ""
Write-Host "  ======================================" -ForegroundColor DarkCyan
Write-Host "  OK Registered: $succeeded" -ForegroundColor Green
Write-Host "  XX Failed:     $failed" -ForegroundColor Red
Write-Host "  ======================================" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Done!" -ForegroundColor Green
Write-Host ""
