import os, re
def fix(p):
    with open(p, 'r', encoding='utf8') as f: c = f.read()
    c = c.replace('func runAddIgnore(args []string) error', 'func runAddIgnore(args []string) *apperror.AppError')
    c = c.replace('func runAddAttributes(args []string) error', 'func runAddAttributes(args []string) *apperror.AppError')
    c = c.replace('func executeAddTemplate(spec addTemplateSpec, args []string) {', 'func executeAddTemplate(spec addTemplateSpec, args []string) *apperror.AppError {')
    c = c.replace('flags, langs := parseAddTemplateArgs(spec, args)', 'flags, langs, err := parseAddTemplateArgs(spec, args)\n\tif err != nil { return err }')
    c = c.replace('fmt.Fprintln(os.Stderr, "  ? Not inside a Git repository.")\n\t\tfmt.Fprintln(os.Stderr, "    Run this from the root of a repo (where .git/ lives).")\n\t\tos.Exit(1)', 'return apperror.New("Not inside a Git repository.", "E9000", nil)')
    c = c.replace('fmt.Fprintf(os.Stderr, "  ? %v\\n", err)\n\t\tos.Exit(1)', 'return apperror.Wrap(err, "resolve templates", nil)')
    c = c.replace('fmt.Fprintf(os.Stderr, "  ? Could not locate repo root: %v\\n", err)\n\t\tos.Exit(1)', 'return apperror.Wrap(err, "locate repo root", nil)')
    c = c.replace('printAddTemplateDryRun(target, tag, body)\n\n\t\treturn\n\t}', 'printAddTemplateDryRun(target, tag, body)\n\n\t\treturn nil\n\t}')
    c = c.replace('if mergeErr != nil {\n\t\tfmt.Fprintf(os.Stderr, "  ? Could not merge into %s: %v\\n", target, mergeErr)\n\t\tos.Exit(1)\n\t}', 'if mergeErr != nil {\n\t\treturn apperror.Wrap(mergeErr, "merge error", nil)\n\t}')
    c = c.replace('printAddTemplateSummary(spec, res)\n}', 'printAddTemplateSummary(spec, res)\n\treturn nil\n}')
    c = c.replace('func parseAddTemplateArgs(spec addTemplateSpec, args []string) (addTemplateFlags, []string) {', 'func parseAddTemplateArgs(spec addTemplateSpec, args []string) (addTemplateFlags, []string, *apperror.AppError) {')
    c = c.replace('if err := fs.Parse(args); err != nil {\n\t\tfmt.Fprintf(os.Stderr, "  ? Could not parse flags: %v\\n", err)\n\t\tos.Exit(1)\n\t}', 'if err := fs.Parse(args); err != nil {\n\t\treturn addTemplateFlags{}, nil, apperror.Wrap(err, "parse flags", nil)\n\t}')
    c = c.replace('return addTemplateFlags{dryRun: *dryRun}, normalizeLangs(fs.Args())\n}', 'return addTemplateFlags{dryRun: *dryRun}, normalizeLangs(fs.Args()), nil\n}')
    c = c.replace('executeAddTemplate(addTemplateSpec{\n\t\tkind:        "ignore",\n\t\tsubcommand:  "ignore",\n\t\ttargetName:  ".gitignore",\n\t\tbannerLabel: "merge curated .gitignore template block",\n\t}, args)\n\treturn nil', 'return executeAddTemplate(addTemplateSpec{\n\t\tkind:        "ignore",\n\t\tsubcommand:  "ignore",\n\t\ttargetName:  ".gitignore",\n\t\tbannerLabel: "merge curated .gitignore template block",\n\t}, args)')
    c = c.replace('executeAddTemplate(addTemplateSpec{\n\t\tkind:        "attributes",\n\t\tsubcommand:  "attributes",\n\t\ttargetName:  ".gitattributes",\n\t\tbannerLabel: "merge curated .gitattributes template block",\n\t}, args)\n\treturn nil', 'return executeAddTemplate(addTemplateSpec{\n\t\tkind:        "attributes",\n\t\tsubcommand:  "attributes",\n\t\ttargetName:  ".gitattributes",\n\t\tbannerLabel: "merge curated .gitattributes template block",\n\t}, args)')
    
    with open(p, 'w', encoding='utf8') as f: f.write(c)
fix('gitmap/cmd/addignoreattrs.go')
