// Package helptext — catalog.go defines topic catalog metadata.
package helpdoc

import (
	"strings"
)

var topicSummaries = map[string]string{
	"pending-commits":             "Discover uncommitted modifications and unpushed commits with tree view remediation and batch fix options.",
	"pc":                          "Discover uncommitted modifications and unpushed commits with tree view remediation and batch fix options.",
	"new-commands":                "Catalog and search recent CLI commands added in the last 100 commits with syntax and usage examples.",
	"nc":                          "Catalog and search recent CLI commands added in the last 100 commits with syntax and usage examples.",
	"push-fix":                    "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"pf":                          "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"pfx":                         "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"pushfix":                     "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"fix-push":                    "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"push fix":                    "Autonomous diagnosis, SSH key synchronization, dual-profile config healing, and direct GitHub push recovery.",
	"commit-in":                   "Comprehensive commit automation engine with JSON author rotation, SEO templates, deduplication heuristics, and AST function intelligence.",
	"commit-push-chore":           "Stages all changes, commits with a \"Chore: \" prefix, and pushes.",
	"cpc":                         "Stages all changes, commits with a \"Chore: \" prefix, and pushes.",
	"commit-push-feature":         "Stages all changes, commits with a \"Feature: \" prefix, and pushes.",
	"cpf":                         "Stages all changes, commits with a \"Feature: \" prefix, and pushes.",
	"commit-push-bug":             "Stages all changes, commits with a \"Bug: \" prefix, and pushes.",
	"cpb":                         "Stages all changes, commits with a \"Bug: \" prefix, and pushes.",
	"commit-push-release":         "Stages all changes, commits with a \"Release: \" prefix, and pushes.",
	"cpr":                         "Stages all changes, commits with a \"Release: \" prefix, and pushes.",
	"pull-commit-push":            "Pulls latest rebase, stages all changes, commits with a message, and pushes.",
	"pcp":                         "Pulls latest rebase, stages all changes, commits with a message, and pushes.",
	"clone-only-missing":          "Clone only missing repositories from JSON manifests or URLs, skipping existing directories on disk without pulling.",
	"com":                         "Clone only missing repositories from JSON manifests or URLs, skipping existing directories on disk without pulling.",
	"commitin":                    "Comprehensive commit automation engine with JSON author rotation, SEO templates, deduplication heuristics, and AST function intelligence.",
	"commit-write":                "Comprehensive commit automation engine with JSON author rotation, SEO templates, deduplication heuristics, and AST function intelligence.",
	"os":                          "Cross-platform OS configuration, updates, mirror auto-repair, and symlink diagnostic utilities.",
	"os-update":                   "Cross-platform OS configuration, updates, mirror auto-repair, and symlink diagnostic utilities.",
	"os-autologin":                "Configure OS auto-login credentials (Windows & Ubuntu) with interactive 3-parameter credentials or flags.",
	"autologin":                   "Configure OS auto-login credentials (Windows & Ubuntu) with interactive 3-parameter credentials or flags.",
	"os-tweak":                    "Manage Windows desktop tweaks: classic right-click context menu, Start menu layout, Ultimate Performance power, and hibernation.",
	"tweak":                       "Manage Windows desktop tweaks: classic right-click context menu, Start menu layout, Ultimate Performance power, and hibernation.",
	"os-dm":                       "Inspect and configure Linux Display Managers (GDM3, LightDM, SDDM), session types, and Wayland compatibility.",
	"dm":                          "Inspect and configure Linux Display Managers (GDM3, LightDM, SDDM), session types, and Wayland compatibility.",
	"os-dns":                      "Inspect, benchmark, switch, and revert system DNS servers across network adapters.",
	"dns":                         "Inspect, benchmark, switch, and revert system DNS servers across network adapters.",
	"os-theme":                    "Switch desktop appearance between Dark Mode and Light Mode across Windows and Linux.",
	"theme":                       "Switch desktop appearance between Dark Mode and Light Mode across Windows and Linux.",
	"fix-mirrors":                 "Cross-platform OS configuration, updates, mirror auto-repair, and symlink diagnostic utilities.",
	"fix-link":                    "Inspect, validate, and repair broken symlinks, VMware shared directories, and workstation desktop links.",
	"fixlink":                     "Inspect, validate, and repair broken symlinks, VMware shared directories, and workstation desktop links.",
	"fl":                          "Inspect, validate, and repair broken symlinks, VMware shared directories, and workstation desktop links.",
	"install":                     "Cross-platform developer tools, runtimes, AI models, custom scripts, and workstation profiles installation manager.",
	"in":                          "Cross-platform developer tools, runtimes, AI models, custom scripts, and workstation profiles installation manager.",
	"cargo":                       "Rust Cargo package manager and compiler toolchain runner with automatic install suggestions.",
	"crg":                         "Rust Cargo package manager and compiler toolchain runner with automatic install suggestions.",
	"installer":                   "Multi-OS installer management, universal Unix execution ordering, Git-direct auto-committing exports, and versioning.",
	"power":                       "Cross-platform OS screen timeout and sleep management framework with SQLite state tracking and restore profiles.",
	"pw":                          "Cross-platform OS screen timeout and sleep management framework with SQLite state tracking and restore profiles.",
	"pwr":                         "Cross-platform OS screen timeout and sleep management framework with SQLite state tracking and restore profiles.",
	"vmware":                      "VMware guest shared folder mounting, open-vm-tools management, desktop symlinks, and crontab persistence.",
	"vm":                          "VMware guest shared folder mounting, open-vm-tools management, desktop symlinks, and crontab persistence.",
	"nginx":                       "High-performance HTTP server, reverse proxy, virtual host management, configuration testing, and reload operations.",
	"ngx":                         "High-performance HTTP server, reverse proxy, virtual host management, configuration testing, and reload operations.",
	"ssh":                         "SSH key pair generation, credential management, host machine enrollment, remote execution, and cluster connectivity.",
	"ssh-join":                    "First-class SSH machine enrollment by user@ip or IP, host alias registration, public key authorization, and instant host recall.",
	"sj":                          "First-class SSH machine enrollment by user@ip or IP, host alias registration, public key authorization, and instant host recall.",
	"ssh-join-add":                "Enroll an SSH target machine by user@ip or IP with an alias and optional public key authorization.",
	"ssh-join-add-with-pass":      "Enroll an SSH machine with RSA-encrypted password storage for seamless auto-login.",
	"ssh-join-add-pass":           "Enroll an SSH machine with RSA-encrypted password storage for seamless auto-login.",
	"ssh-join-scan":               "Scan local subnet or CIDR network for machines with open SSH port 22.",
	"ssh-join-status":             "Inspect connectivity, latency, and health of registered SSH machines.",
	"sj-add":                      "Enroll an SSH target machine by user@ip or IP with an alias and optional public key authorization.",
	"sj-add-with-pass":            "Enroll an SSH machine with RSA-encrypted password storage for seamless auto-login.",
	"sj-add-pass":                 "Enroll an SSH machine with RSA-encrypted password storage for seamless auto-login.",
	"sj-scan":                     "Scan local subnet or CIDR network for machines with open SSH port 22.",
	"sj-status":                   "Inspect connectivity, latency, and health of registered SSH machines.",
	"cluster":                     "Comprehensive cluster management for multi-node topology, remote execution, script deployment, and Ubuntu provisioning.",
	"cluster-add":                 "Enroll new nodes into cluster topology and SSH host registry with alias registration and key authorization.",
	"cluster-join":                "Join nodes to cluster using SSH enrollment and automated host registration.",
	"cluster-node":                "Provision and configure Ubuntu cluster nodes with static Netplan IP, base tools, oh-my-zsh users, and cleanup recipes.",
	"cluster-nodes":               "List registered nodes in the cluster database with display ID, role, OS, and reachability status.",
	"cluster-status":              "Inspect cluster connectivity, node health, heartbeat records, and ping round-trip latency.",
	"cluster-remove":              "Remove and unregister nodes from the cluster topology and SSH host registry.",
	"cluster-bootstrap":           "Bootstrap cluster nodes with RSA keys, passwordless sudo, and automated enrollment.",
	"cluster-exec":                "Execute remote command across targeted cluster nodes",
	"cluster-run-script":          "Deploy and execute local scripts remotely across cluster nodes with base64 staging and automatic cleanup.",
	"cluster-import":              "Import cluster topology from JSON configuration and enroll control plane and worker nodes.",
	"cluster-init":                "Generate starter cluster topology JSON configuration file (01-config.json) automatically from the terminal.",
	"cluster-template":            "Generate starter cluster topology JSON configuration file (01-config.json) automatically from the terminal.",
	"cluster-k8s":                 "Manage Kubernetes cluster lifecycle, runtime, and components",
	"cluster-k8s-init":            "Initialize Kubernetes control plane",
	"cluster-k8s-join":            "Join worker nodes to Kubernetes control plane",
	"cluster-k8s-helm":            "Deploy Helm and storage class provisioners",
	"cluster-install":             "Install GitMap remotely across cluster nodes via SSH using curl/PowerShell one-liners and auto-bootstrapping.",
	"schedule-shutdown":           "Schedule operating system shutdown with flexible durations, state tracking, status inspection, and cancellation.",
	"schedule-restart":            "Schedule operating system reboot with flexible durations, state tracking, status inspection, and cancellation.",
	"os-ai-clean":                 "Scan, analyze, and safely purge Google Antigravity AI caches, transcripts, and temporary installer files.",
	"ai-clean":                    "Scan, analyze, and safely purge Google Antigravity AI caches, transcripts, and temporary installer files.",
	"servers-clients":             "Distributed fan-out execution across cluster nodes",
	"sc":                          "Short alias for servers-clients",
	"clients":                     "Target clients in servers-clients topology",
	"agy-fix-pipeline":            "Extract failing pipeline error logs and combine with CI/CD fix prompt for Antigravity IDE into clipboard and active temp file.",
	"agy-log":                     "Inspect Antigravity decision audit logs and operational traces recorded in SQLite Split-DB.",
	"fix-pipeline":                "Extract failing pipeline error logs and combine with CI/CD fix prompt for Antigravity IDE into clipboard and active temp file.",
	"author":                      "Display credentials, background, and innovations of GitMap's creator & system architect MD ALIM UL KARIM.",
	"sponsor":                     "Display information about GitMap's official sponsor and engineering partner RISEUP ASIA LLC (https://riseup-asia.com).",
	"credits":                     "Display creator, sponsor, and engineering partner acknowledgments.",
	"task":                        "Manage and inspect pending and completed task execution queues, history, and undo/redo operations.",
	"tasks":                       "Manage and inspect pending and completed task execution queues, history, and undo/redo operations.",
	"agy":                         "Manage Google Antigravity workspaces, rerun historical prompts with prefix verification templates, inspect prompt diffs across projects in non-admin VS Code, and orchestrate remote execution.",
	"agm":                         "Manage and install Antigravity Manager GUI desktop application and tools locally or across remote SSH fleet nodes concurrently.",
	"antigravity":                 "Manage Google Antigravity workspaces, rerun historical prompts with prefix verification templates, inspect prompt diffs across projects in non-admin VS Code, and orchestrate remote execution.",
	"rerun":                       "Rerun active Antigravity prompts with optional IDE restart, media attachments, and queued prefix check.",
	"rr":                          "Rerun active Antigravity prompts with optional IDE restart, media attachments, and queued prefix check.",
	"rra":                         "Rerun active Antigravity prompts across all running projects.",
	"rrq":                         "Re-inject queued Antigravity prompts with completion verification prefixes.",
	"rerun-restart":               "Restart Antigravity IDE and replay active prompt.",
	"rerun-all":                   "Rerun active Antigravity prompts across all running projects.",
	"rerun-queue":                 "Re-inject queued Antigravity prompts with completion verification prefixes.",
	"pipeline":                    "Query live CI/CD pipeline runs, calculate remaining wait times (ETA), fetch step failure logs, export telemetry, clear local databases, and feed errors to Antigravity.",
	"pl":                          "Query live CI/CD pipeline runs, calculate remaining wait times (ETA), fetch step failure logs, export telemetry, clear local databases, and feed errors to Antigravity.",
	"prompts-template":            "Manage reusable Antigravity prompt prefix and verification templates with JSON storage, add, edit, list, remove, export, and import operations.",
	"prompt-template":             "Manage reusable Antigravity prompt prefix and verification templates with JSON storage, add, edit, list, remove, export, and import operations.",
	"prompt_templates":            "Manage reusable Antigravity prompt prefix and verification templates with JSON storage, add, edit, list, remove, export, and import operations.",
	"pt":                          "Manage reusable Antigravity prompt prefix and verification templates with JSON storage, add, edit, list, remove, export, and import operations.",
	"storage":                     "Display disk drives, storage volumes, mount points, filesystem space utilization, repository SQLite databases, and restore database from snapshots.",
	"schedule":                    "Manage scheduled tasks, macro schedules, OS startup tasks, isolated split SQLite databases, run history, and execution logs.",
	"schedules":                   "Manage scheduled tasks, macro schedules, OS startup tasks, isolated split SQLite databases, run history, and execution logs.",
	"ai":                          "Native AI scripts automation catalog, streaming execution, and repository autofix engine.",
	"scripts":                     "Native AI scripts automation catalog, streaming execution, and repository autofix engine.",
	"run-smart":                   "Execute smart incremental Go test runner on changed packages only using OS temp precompilation and Quad Runner.",
	"run-incremental":             "Execute smart incremental Go test runner on changed packages only using OS temp precompilation and Quad Runner.",
	"smart":                       "Execute smart incremental Go test runner on changed packages only using OS temp precompilation and Quad Runner.",
	"test":                        "Execute smart incremental Go test runner on changed packages only using OS temp precompilation and Quad Runner.",
	"ai-create":                   "Scaffold a new AI automation script skeleton with standard archetypes, flags, and error handling.",
	"ai-list":                     "List registered and dynamically discovered AI scripts with status and category filtering.",
	"ai-run":                      "Execute a registered or dynamic AI automation script by number, slug, or alias with streaming output.",
	"ai-fix":                      "Run standardized repository autofix targets for coding guidelines, newlines, naming, and paths.",
	"automation":                  "High-performance native Go automation, multi-core search, polyglot newline normalization, and side-by-side execution benchmarks.",
	"auto":                        "High-performance native Go automation, multi-core search, polyglot newline normalization, and side-by-side execution benchmarks.",
	"aum":                         "High-performance native Go automation, multi-core search, polyglot newline normalization, and side-by-side execution benchmarks.",
	"py-auto":                     "High-performance native Go automation, multi-core search, polyglot newline normalization, and side-by-side execution benchmarks.",
	"automation-search":           "Multi-core streaming search across repository files with lazy regex or literal match.",
	"automation-newlines":         "Polyglot CRLF to LF and trailing whitespace normalizer.",
	"automation-benchmark":        "Run side-by-side Go vs Python execution benchmarks.",
	"automation-relative-paths":   "Audit and sanitize forbidden absolute filesystem paths in documentation and code.",
	"automation-naming":           "Audit boolean comparison anti-patterns and affirmative naming conventions.",
	"automation-result-wrapper":   "Audit Go functions returning multi-value map/slice error tuples.",
	"automation-params":           "Audit function signatures for argument reduction and parameter structs.",
	"automation-enums":            "Audit enums for *Type suffixes and ban raw numeric rune casts.",
	"automation-topology":         "Analyze codebase entry points, database schemas, CI workflows, and polyglot distributions with SQLite caching.",
	"automation-db-generate":      "Inspect SQLite database tables and generate type-safe Go structs and TypeScript interfaces.",
	"automation-db-migrate":       "Execute transactional SQLite migrations with rollback protection and history tracking.",
	"automation-schema-audit":     "Audit SQLite schemas against PascalCase naming, primary key, and affirmative boolean standards.",
	"automation-preflight":        "Run multi-core CI/CD preflight checks across CPU cores with real-time progress percentages.",
	"automation-test-inventory":   "Discover unit and integration tests, generate duration baselines, and manage atomic change tracking.",
	"automation-purge-actions":    "Query GitHub Actions API and purge obsolete workflow logs and artifacts to maintain 0.0 GB footprint.",
	"automation-smoke-test":       "Cross-platform validator for installer scripts and tool binary PATH availability.",
	"automation-version-sync":     "Audit and synchronize version string alignment across constants, package.json, Cargo.toml, and specs.",
	"automation-release-bump":     "Compute next semantic version number based on commit types and execute release updates.",
	"automation-milestones":       "Query GitHub milestone issues and PRs and format structured release notes for changelogs.",
	"automation-help-audit":       "Scan CLI AST command definitions and verify documentation parity against cli/helptext.",
	"automation-plan-consolidate": "Cluster completed tasks and subtasks into milestone summaries with zero architectural loss.",
	"automation-doc-links":        "Audit and autofix relative markdown links and cross-references across specs and documentation.",
	"automation-spec-migrate":     "Re-sequence specification file prefixes and update cross-references across repository files.",
	"automation-clean-artifacts":  "Safely purge build binaries, test dumps, pycache, and temporary directories.",
	"automation-changed-files":    "Discover modified, staged, and untracked files relative to origin/main or specified base commit.",
	"automation-purge-history":    "Trace and identify large historical git blobs without rewriting recent commit lineage.",
	"automation-format-go":        "AST-aware Go code formatter organizing imports and enforcing UTF-8 BOM-free LF encoding.",
	"vscode":                      "Manage VS Code workspace integrations, Project Manager projects.json, profiles, group categorization, and automatic repair.",
	"vscode-repair":               "Diagnose & repair VS Code startup crashes (Chromium ICU data file error) and synchronize Project Manager projects.json across modern and legacy paths.",
	"lap":                         "Inspect Antigravity projects active in the last N hours (default 24h) with conversation prompt trees, pagination, and JSON export.",
	"last-active-projects":        "Inspect Antigravity projects active in the last N hours (default 24h) with conversation prompt trees, pagination, and JSON export.",
	"rwi":                         "Resolve project by 24h sequence, ID, alias, or path and conversation (<convid|P1>), then inject prompt text or markdown file.",
	"rerun-with-id":               "Resolve project by 24h sequence, ID, alias, or path and conversation (<convid|P1>), then inject prompt text or markdown file.",
	"rwc":                         "Auto-resolve project and conversation from <convid|P1> in the 24h SQLite sequence cache and inject prompt text or file.",
	"rerun-with-convid":           "Auto-resolve project and conversation from <convid|P1> in the 24h SQLite sequence cache and inject prompt text or file.",
	"rwp":                         "Auto-resolve project and conversation from short prompt ID (<P1|convid>) in the 24h SQLite sequence cache and inject prompt.",
	"rerun-with-prompt-id":        "Auto-resolve project and conversation from short prompt ID (<P1|convid>) in the 24h SQLite sequence cache and inject prompt.",
	"add-read":                    "Add current repository (.) or explicit path to Antigravity workspace registry and immediately dispatch Read Memory prompt.",
	"ar":                          "Add current repository (.) or explicit path to Antigravity workspace registry and immediately dispatch Read Memory prompt.",
	"machine":                     "Inspect, set, change, or revert local and SSH fleet machine hostname and network identity.",
	"alias":                       "Manage repository aliases and local/SSH fleet machine network aliases (auto-defaulting to Local IPv4).",
	"telegram":                    "Configure two-way Telegram chatbot notifications and remote chat command execution (/status, /rp, /lap, /rwi, /asw).",
	"email":                       "Configure speed SMTP email notifications and alert verification.",
	"settings":                    "Manage unified speed settings for LAP default lookback hours (24), account-switch threshold (15%), Telegram bot, Email, and Machine identity.",
	"account-switch":              "Fast-forward switch Antigravity account automatically upon reaching credit threshold (15% remaining prod / 98% E2E test).",
	"asw":                         "Fast-forward switch Antigravity account automatically upon reaching credit threshold (15% remaining prod / 98% E2E test).",
	"fast-forward":                "Fast-forward switch Antigravity account automatically upon reaching credit threshold (15% remaining prod / 98% E2E test).",
	"ff":                          "Fast-forward switch Antigravity account automatically upon reaching credit threshold (15% remaining prod / 98% E2E test).",
	"rs":                          "Store secrets, .env files, folders, and inline tokens into the sequenced repo-secrets vault (XX-<repo>/01-<slug>.ext) with auto-commit and push.",
	"repo-secrets":                "Store secrets, .env files, folders, and inline tokens into the sequenced repo-secrets vault (XX-<repo>/01-<slug>.ext) with auto-commit and push.",
	"rc":                          "Archive reusable PowerShell (.ps1) scripts, test harnesses, and folders into repo-cache (XX-<repo>/01-<slug>.ext) with auto-commit and push.",
	"repo-cache":                  "Archive reusable PowerShell (.ps1) scripts, test harnesses, and folders into repo-cache (XX-<repo>/01-<slug>.ext) with auto-commit and push.",
	"repo-storage":                "Archive reusable PowerShell (.ps1) scripts, test harnesses, and folders into repo-cache (XX-<repo>/01-<slug>.ext) with auto-commit and push.",
	"pull":                        "Pull latest changes for a single repository, group, or all tracked repositories with optional companion repository probing (--probe).",
	"pull-all":                    "Batch-pull every tracked repository in the catalog with fast concise progress or full table (--status), SSH fleet delegation (--ssh), and companion repository probing (--probe).",
	"pa":                          "Fast concise batch-pull of all tracked repositories with optional companion repository probing (--probe), status table (--status), and JSON export (--json).",
	"pat":                         "Batch-pull every tracked repository in the catalog and display the full post-pull status table.",
	"nodes":                       "Unified fleet infrastructure command aggregating nodes across SSH, Cluster DB, and Server-Client networks with live probing and machine ping.",
	"node":                        "Unified fleet infrastructure command aggregating nodes across SSH, Cluster DB, and Server-Client networks with live probing and machine ping.",
	"nodes-cfr":                   "Clone, remediate, and synchronize repositories across multi-node SSH cluster and local host with pre-flight version discovery.",
	"nodes-clone":                 "Fan-out repository cloning asynchronously across local host and remote SSH fleet nodes with relative workdir mirroring.",
	"nodes-cfrp":                  "Clone, fix, and promote repositories to public visibility across remote SSH fleet nodes.",
	"cfr":                         "Clone, remediate, and synchronize repository locally or across fleet nodes.",
	"cfrp":                        "Clone, remediate, and make repository public locally or across fleet nodes.",
	"clone-except-self":           "Execute repository cloning strictly across remote SSH fleet nodes, skipping the local master workstation.",
	"ping":                        "Run machine ping command and network reachability probes concurrently against all fleet nodes with tabular terminal display.",
	"nodes-ping":                  "Run machine ping command and network reachability probes concurrently against all fleet nodes with tabular terminal display.",
	"pull-error":                  "Inspect, query, filter, and remediate persistent Git pull error diagnostics and stack traces recorded across local or SSH fleet repositories.",
	"pull-errors":                 "Inspect, query, filter, and remediate persistent Git pull error diagnostics and stack traces recorded across local or SSH fleet repositories.",
	"pulle":                       "Inspect, query, filter, and remediate persistent Git pull error diagnostics and stack traces recorded across local or SSH fleet repositories.",
	"pull-e":                      "Inspect, query, filter, and remediate persistent Git pull error diagnostics and stack traces recorded across local or SSH fleet repositories.",
	"devtool":                     "Developer tools cache discovery, hierarchical tree analysis, SQLite Split-DB caching, and high-speed multi-ecosystem cache reclamation.",
	"devtools":                    "Developer tools cache discovery, hierarchical tree analysis, SQLite Split-DB caching, and high-speed multi-ecosystem cache reclamation.",
	"clean-dev":                   "Developer tools cache discovery, hierarchical tree analysis, SQLite Split-DB caching, and high-speed multi-ecosystem cache reclamation.",
	"ignore":                      "Audit, configure, and enforce .gitignore patterns across repositories with SQLite Split-DB check caching, frequency intervals, and automated remediation.",
	"fia":                         "Audit and remediate .gitignore patterns across repositories with SQLite Split-DB check caching and automated remediation.",
	"fias":                        "Audit and remediate .gitignore patterns across repositories with SQLite Split-DB check caching and automated remediation.",
}

// GetTopicDetailedSummary returns documentation content for a specific command topic.
func GetTopicDetailedSummary(topic string) string {
	norm := strings.ToLower(topic)
	if summary, hasSummary := topicSummaries[norm]; hasSummary {
		return summary
	}

	return "Gitmap command line utilities."
}
