// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/gitmap/repodb/enums"
)

// ScanFileSequence maps a database row scanner to a FileSequence entity.
func ScanFileSequence(row dbengine.RowScanner) (*FileSequence, error) {
	var item FileSequence
	var (
		raw_FileSequenceId any
		raw_Directory      any
		raw_Filename       any
		raw_SequenceNumber any
		raw_BaseName       any
		raw_UpdatedAt      any
	)
	err := row.Scan(
		&raw_FileSequenceId,
		&raw_Directory,
		&raw_Filename,
		&raw_SequenceNumber,
		&raw_BaseName,
		&raw_UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.FileSequenceId = dbengine.ScanUint64(raw_FileSequenceId)
	item.Directory = dbengine.ScanString(raw_Directory)
	item.Filename = dbengine.ScanString(raw_Filename)
	item.SequenceNumber = dbengine.ScanInt(raw_SequenceNumber)
	item.BaseName = dbengine.ScanString(raw_BaseName)
	item.UpdatedAt = dbengine.ScanInt64(raw_UpdatedAt)

	return &item, nil
}

// FileSequenceDbRepo provides typed database repository access for FileSequence.
type FileSequenceDbRepo struct {
	db   *dbengine.DbWrapper
	repo *FileSequenceRepository
}

// NewFileSequenceDbRepo initializes a typed repository for FileSequence.
func NewFileSequenceDbRepo(db *dbengine.DbWrapper) *FileSequenceDbRepo {
	repo := dbengine.NewRepository[FileSequence, enums.FileSequenceFieldType](
		db,
		enums.FileSequenceTable,
		ScanFileSequence,
	)

	return &FileSequenceDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *FileSequenceDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *FileSequenceDbRepo) Repo() *FileSequenceRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *FileSequenceDbRepo) Query() *FileSequenceQueryBuilder {
	return r.repo.Query().Select(enums.FileSequenceDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *FileSequenceDbRepo) QueryBare() *FileSequenceQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *FileSequenceDbRepo) FindAll(ctx context.Context) dbengine.ListResult[FileSequence] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *FileSequenceDbRepo) First(ctx context.Context) dbengine.EntityResult[FileSequence] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *FileSequenceDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

// Insert inserts a new FileSequence record into the database.
func (r *FileSequenceDbRepo) Insert(ctx context.Context, item *FileSequence) dbengine.RowsAffectedResult {
	query := "INSERT INTO FileSequence (FileSequenceId, Directory, Filename, SequenceNumber, BaseName, UpdatedAt) VALUES (?, ?, ?, ?, ?, ?);"
	var id any = item.FileSequenceId
	if item.FileSequenceId == 0 {
		id = nil
	}

	return r.db.ExecRowsAffected(ctx, query, id, item.Directory, item.Filename, item.SequenceNumber, item.BaseName, item.UpdatedAt)
}

// Update updates an existing FileSequence record identified by its primary key.
func (r *FileSequenceDbRepo) Update(ctx context.Context, item *FileSequence) dbengine.RowsAffectedResult {
	query := "UPDATE FileSequence SET Directory = ?, Filename = ?, SequenceNumber = ?, BaseName = ?, UpdatedAt = ? WHERE FileSequenceId = ?;"

	return r.db.ExecRowsAffected(ctx, query, item.Directory, item.Filename, item.SequenceNumber, item.BaseName, item.UpdatedAt, item.FileSequenceId)
}

// DeleteById deletes a FileSequence record by its primary key identifier.
func (r *FileSequenceDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.FileSequenceDb.FileSequenceId, id)
}
