// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/gitmap/repodb/enums"
)

// ScanSequenceHistory maps a database row scanner to a SequenceHistory entity.
func ScanSequenceHistory(row dbengine.RowScanner) (*SequenceHistory, error) {
	var item SequenceHistory
	var (
		raw_SequenceHistoryId any
		raw_Directory         any
		raw_OperationsJson    any
		raw_CreatedAt         any
	)
	err := row.Scan(
		&raw_SequenceHistoryId,
		&raw_Directory,
		&raw_OperationsJson,
		&raw_CreatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.SequenceHistoryId = dbengine.ScanUint64(raw_SequenceHistoryId)
	item.Directory = dbengine.ScanString(raw_Directory)
	item.OperationsJson = dbengine.ScanString(raw_OperationsJson)
	item.CreatedAt = dbengine.ScanInt64(raw_CreatedAt)
	return &item, nil
}

// SequenceHistoryDbRepo provides typed database repository access for SequenceHistory.
type SequenceHistoryDbRepo struct {
	db   *dbengine.DbWrapper
	repo *SequenceHistoryRepository
}

// NewSequenceHistoryDbRepo initializes a typed repository for SequenceHistory.
func NewSequenceHistoryDbRepo(db *dbengine.DbWrapper) *SequenceHistoryDbRepo {
	repo := dbengine.NewRepository[SequenceHistory, enums.SequenceHistoryFieldType](
		db,
		enums.SequenceHistoryTable,
		ScanSequenceHistory,
	)
	return &SequenceHistoryDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *SequenceHistoryDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *SequenceHistoryDbRepo) Repo() *SequenceHistoryRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *SequenceHistoryDbRepo) Query() *SequenceHistoryQueryBuilder {
	return r.repo.Query().Select(enums.SequenceHistoryDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *SequenceHistoryDbRepo) QueryBare() *SequenceHistoryQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *SequenceHistoryDbRepo) FindAll(ctx context.Context) dbengine.ListResult[SequenceHistory] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *SequenceHistoryDbRepo) First(ctx context.Context) dbengine.EntityResult[SequenceHistory] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *SequenceHistoryDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

// Insert inserts a new SequenceHistory record into the database.
func (r *SequenceHistoryDbRepo) Insert(ctx context.Context, item *SequenceHistory) dbengine.RowsAffectedResult {
	query := "INSERT INTO SequenceHistory (SequenceHistoryId, Directory, OperationsJson, CreatedAt) VALUES (?, ?, ?, ?);"
	var id any = item.SequenceHistoryId
	if item.SequenceHistoryId == 0 {
		id = nil
	}
	return r.db.ExecRowsAffected(ctx, query, id, item.Directory, item.OperationsJson, item.CreatedAt)
}

// Update updates an existing SequenceHistory record identified by its primary key.
func (r *SequenceHistoryDbRepo) Update(ctx context.Context, item *SequenceHistory) dbengine.RowsAffectedResult {
	query := "UPDATE SequenceHistory SET Directory = ?, OperationsJson = ?, CreatedAt = ? WHERE SequenceHistoryId = ?;"
	return r.db.ExecRowsAffected(ctx, query, item.Directory, item.OperationsJson, item.CreatedAt, item.SequenceHistoryId)
}

// DeleteById deletes a SequenceHistory record by its primary key identifier.
func (r *SequenceHistoryDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.SequenceHistoryDb.SequenceHistoryId, id)
}
