// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"github.com/alimtvnetwork/gitmap-v28/cli/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/cli/repodb/enums"
)

// Canonical table name constants re-exported from enums package.
const (
	RepoFileTable        = enums.RepoFileTable
	SearchCacheTable     = enums.SearchCacheTable
	FileSequenceTable    = enums.FileSequenceTable
	SequenceHistoryTable = enums.SequenceHistoryTable
	RepoScanLogTable     = enums.RepoScanLogTable
	IndexedRepoTable     = enums.IndexedRepoTable
)

// Dedicated QueryBuilder type aliases.
type (
	// RepoFileQueryBuilder is the dedicated query builder for RepoFile.
	RepoFileQueryBuilder = dbengine.QueryBuilder[RepoFile, enums.RepoFileFieldType]
	// SearchCacheQueryBuilder is the dedicated query builder for SearchCache.
	SearchCacheQueryBuilder = dbengine.QueryBuilder[SearchCache, enums.SearchCacheFieldType]
	// FileSequenceQueryBuilder is the dedicated query builder for FileSequence.
	FileSequenceQueryBuilder = dbengine.QueryBuilder[FileSequence, enums.FileSequenceFieldType]
	// SequenceHistoryQueryBuilder is the dedicated query builder for SequenceHistory.
	SequenceHistoryQueryBuilder = dbengine.QueryBuilder[SequenceHistory, enums.SequenceHistoryFieldType]
	// RepoScanLogQueryBuilder is the dedicated query builder for RepoScanLog.
	RepoScanLogQueryBuilder = dbengine.QueryBuilder[RepoScanLog, enums.RepoScanLogFieldType]
	// IndexedRepoQueryBuilder is the dedicated query builder for IndexedRepo.
	IndexedRepoQueryBuilder = dbengine.QueryBuilder[IndexedRepo, enums.IndexedRepoFieldType]
)

// Dedicated generic Repository type aliases.
type (
	// RepoFileRepository is the dedicated generic repository for RepoFile.
	RepoFileRepository = dbengine.Repository[RepoFile, enums.RepoFileFieldType]
	// SearchCacheRepository is the dedicated generic repository for SearchCache.
	SearchCacheRepository = dbengine.Repository[SearchCache, enums.SearchCacheFieldType]
	// FileSequenceRepository is the dedicated generic repository for FileSequence.
	FileSequenceRepository = dbengine.Repository[FileSequence, enums.FileSequenceFieldType]
	// SequenceHistoryRepository is the dedicated generic repository for SequenceHistory.
	SequenceHistoryRepository = dbengine.Repository[SequenceHistory, enums.SequenceHistoryFieldType]
	// RepoScanLogRepository is the dedicated generic repository for RepoScanLog.
	RepoScanLogRepository = dbengine.Repository[RepoScanLog, enums.RepoScanLogFieldType]
	// IndexedRepoRepository is the dedicated generic repository for IndexedRepo.
	IndexedRepoRepository = dbengine.Repository[IndexedRepo, enums.IndexedRepoFieldType]
)

// Re-exported field enums and registries for backward compatibility.
type (
	// RepoFileFieldType aliases enums.RepoFileFieldType for direct package access.
	RepoFileFieldType = enums.RepoFileFieldType
	// SearchCacheFieldType aliases enums.SearchCacheFieldType for direct package access.
	SearchCacheFieldType = enums.SearchCacheFieldType
	// FileSequenceFieldType aliases enums.FileSequenceFieldType for direct package access.
	FileSequenceFieldType = enums.FileSequenceFieldType
	// SequenceHistoryFieldType aliases enums.SequenceHistoryFieldType for direct package access.
	SequenceHistoryFieldType = enums.SequenceHistoryFieldType
	// RepoScanLogFieldType aliases enums.RepoScanLogFieldType for direct package access.
	RepoScanLogFieldType = enums.RepoScanLogFieldType
	// IndexedRepoFieldType aliases enums.IndexedRepoFieldType for direct package access.
	IndexedRepoFieldType = enums.IndexedRepoFieldType
)

var (
	// RepoFileDb aliases enums.RepoFileDb.
	RepoFileDb = enums.RepoFileDb
	// RepoFileField aliases enums.RepoFileField.
	RepoFileField = enums.RepoFileField
	// SearchCacheDb aliases enums.SearchCacheDb.
	SearchCacheDb = enums.SearchCacheDb
	// SearchCacheField aliases enums.SearchCacheField.
	SearchCacheField = enums.SearchCacheField
	// FileSequenceDb aliases enums.FileSequenceDb.
	FileSequenceDb = enums.FileSequenceDb
	// FileSequenceField aliases enums.FileSequenceField.
	FileSequenceField = enums.FileSequenceField
	// SequenceHistoryDb aliases enums.SequenceHistoryDb.
	SequenceHistoryDb = enums.SequenceHistoryDb
	// SequenceHistoryField aliases enums.SequenceHistoryField.
	SequenceHistoryField = enums.SequenceHistoryField
	// RepoScanLogDb aliases enums.RepoScanLogDb.
	RepoScanLogDb = enums.RepoScanLogDb
	// RepoScanLogField aliases enums.RepoScanLogField.
	RepoScanLogField = enums.RepoScanLogField
	// IndexedRepoDb aliases enums.IndexedRepoDb.
	IndexedRepoDb = enums.IndexedRepoDb
	// IndexedRepoField aliases enums.IndexedRepoField.
	IndexedRepoField = enums.IndexedRepoField
)
