// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/cli/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/cli/repodb/enums"
)

// ScanIndexedRepo maps a database row scanner to a IndexedRepo entity.
func ScanIndexedRepo(row dbengine.RowScanner) (*IndexedRepo, error) {
	var item IndexedRepo
	var (
		raw_IndexedRepoId   any
		raw_Path            any
		raw_Slug            any
		raw_MigratedVersion any
		raw_CreatedAt       any
		raw_UpdatedAt       any
	)
	err := row.Scan(
		&raw_IndexedRepoId,
		&raw_Path,
		&raw_Slug,
		&raw_MigratedVersion,
		&raw_CreatedAt,
		&raw_UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.IndexedRepoId = dbengine.ScanUint64(raw_IndexedRepoId)
	item.Path = dbengine.ScanString(raw_Path)
	item.Slug = dbengine.ScanString(raw_Slug)
	item.MigratedVersion = dbengine.ScanInt(raw_MigratedVersion)
	item.CreatedAt = dbengine.ScanInt64(raw_CreatedAt)
	item.UpdatedAt = dbengine.ScanInt64(raw_UpdatedAt)

	return &item, nil
}

// IndexedRepoDbRepo provides typed database repository access for IndexedRepo.
type IndexedRepoDbRepo struct {
	db   *dbengine.DbWrapper
	repo *IndexedRepoRepository
}

// NewIndexedRepoDbRepo initializes a typed repository for IndexedRepo.
func NewIndexedRepoDbRepo(db *dbengine.DbWrapper) *IndexedRepoDbRepo {
	repo := dbengine.NewRepository[IndexedRepo, enums.IndexedRepoFieldType](
		db,
		enums.IndexedRepoTable,
		ScanIndexedRepo,
	)

	return &IndexedRepoDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *IndexedRepoDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *IndexedRepoDbRepo) Repo() *IndexedRepoRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *IndexedRepoDbRepo) Query() *IndexedRepoQueryBuilder {
	return r.repo.Query().Select(enums.IndexedRepoDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *IndexedRepoDbRepo) QueryBare() *IndexedRepoQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *IndexedRepoDbRepo) FindAll(ctx context.Context) dbengine.ListResult[IndexedRepo] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *IndexedRepoDbRepo) First(ctx context.Context) dbengine.EntityResult[IndexedRepo] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *IndexedRepoDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

// Insert inserts a new IndexedRepo record into the database.
func (r *IndexedRepoDbRepo) Insert(ctx context.Context, item *IndexedRepo) dbengine.RowsAffectedResult {
	query := "INSERT INTO IndexedRepo (IndexedRepoId, Path, Slug, MigratedVersion, CreatedAt, UpdatedAt) VALUES (?, ?, ?, ?, ?, ?);"
	var id any = item.IndexedRepoId
	if item.IndexedRepoId == 0 {
		id = nil
	}

	return r.db.ExecRowsAffected(ctx, query, id, item.Path, item.Slug, item.MigratedVersion, item.CreatedAt, item.UpdatedAt)
}

// Update updates an existing IndexedRepo record identified by its primary key.
func (r *IndexedRepoDbRepo) Update(ctx context.Context, item *IndexedRepo) dbengine.RowsAffectedResult {
	query := "UPDATE IndexedRepo SET Path = ?, Slug = ?, MigratedVersion = ?, CreatedAt = ?, UpdatedAt = ? WHERE IndexedRepoId = ?;"

	return r.db.ExecRowsAffected(ctx, query, item.Path, item.Slug, item.MigratedVersion, item.CreatedAt, item.UpdatedAt, item.IndexedRepoId)
}

// DeleteById deletes a IndexedRepo record by its primary key identifier.
func (r *IndexedRepoDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.IndexedRepoDb.IndexedRepoId, id)
}
