// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/cli/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/cli/repodb/enums"
)

// ScanRepoScanLog maps a database row scanner to a RepoScanLog entity.
func ScanRepoScanLog(row dbengine.RowScanner) (*RepoScanLog, error) {
	var item RepoScanLog
	var (
		raw_RepoScanLogId any
		raw_RepoId        any
		raw_RepoSlug      any
		raw_Action        any
		raw_Status        any
		raw_ErrorMessage  any
		raw_Details       any
		raw_Notes         any
		raw_Comments      any
		raw_CreatedAt     any
	)
	err := row.Scan(
		&raw_RepoScanLogId,
		&raw_RepoId,
		&raw_RepoSlug,
		&raw_Action,
		&raw_Status,
		&raw_ErrorMessage,
		&raw_Details,
		&raw_Notes,
		&raw_Comments,
		&raw_CreatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.RepoScanLogId = dbengine.ScanUint64(raw_RepoScanLogId)
	item.RepoId = dbengine.ScanInt64(raw_RepoId)
	item.RepoSlug = dbengine.ScanString(raw_RepoSlug)
	item.Action = dbengine.ScanString(raw_Action)
	item.Status = dbengine.ScanString(raw_Status)
	item.ErrorMessage = dbengine.ScanString(raw_ErrorMessage)
	item.Details = dbengine.ScanString(raw_Details)
	item.Notes = dbengine.ScanString(raw_Notes)
	item.Comments = dbengine.ScanString(raw_Comments)
	item.CreatedAt = dbengine.ScanString(raw_CreatedAt)

	return &item, nil
}

// RepoScanLogDbRepo provides typed database repository access for RepoScanLog.
type RepoScanLogDbRepo struct {
	db   *dbengine.DbWrapper
	repo *RepoScanLogRepository
}

// NewRepoScanLogDbRepo initializes a typed repository for RepoScanLog.
func NewRepoScanLogDbRepo(db *dbengine.DbWrapper) *RepoScanLogDbRepo {
	repo := dbengine.NewRepository[RepoScanLog, enums.RepoScanLogFieldType](
		db,
		enums.RepoScanLogTable,
		ScanRepoScanLog,
	)

	return &RepoScanLogDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *RepoScanLogDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *RepoScanLogDbRepo) Repo() *RepoScanLogRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *RepoScanLogDbRepo) Query() *RepoScanLogQueryBuilder {
	return r.repo.Query().Select(enums.RepoScanLogDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *RepoScanLogDbRepo) QueryBare() *RepoScanLogQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *RepoScanLogDbRepo) FindAll(ctx context.Context) dbengine.ListResult[RepoScanLog] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *RepoScanLogDbRepo) First(ctx context.Context) dbengine.EntityResult[RepoScanLog] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *RepoScanLogDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

// Insert inserts a new RepoScanLog record into the database.
func (r *RepoScanLogDbRepo) Insert(ctx context.Context, item *RepoScanLog) dbengine.RowsAffectedResult {
	query := "INSERT INTO RepoScanLog (RepoScanLogId, RepoId, RepoSlug, Action, Status, ErrorMessage, Details, Notes, Comments, CreatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"
	var id any = item.RepoScanLogId
	if item.RepoScanLogId == 0 {
		id = nil
	}

	return r.db.ExecRowsAffected(ctx, query, id, item.RepoId, item.RepoSlug, item.Action, item.Status, item.ErrorMessage, item.Details, item.Notes, item.Comments, item.CreatedAt)
}

// Update updates an existing RepoScanLog record identified by its primary key.
func (r *RepoScanLogDbRepo) Update(ctx context.Context, item *RepoScanLog) dbengine.RowsAffectedResult {
	query := "UPDATE RepoScanLog SET RepoId = ?, RepoSlug = ?, Action = ?, Status = ?, ErrorMessage = ?, Details = ?, Notes = ?, Comments = ?, CreatedAt = ? WHERE RepoScanLogId = ?;"

	return r.db.ExecRowsAffected(ctx, query, item.RepoId, item.RepoSlug, item.Action, item.Status, item.ErrorMessage, item.Details, item.Notes, item.Comments, item.CreatedAt, item.RepoScanLogId)
}

// DeleteById deletes a RepoScanLog record by its primary key identifier.
func (r *RepoScanLogDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.RepoScanLogDb.RepoScanLogId, id)
}
