// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"
	"database/sql"
	"runtime"
	"time"

	"github.com/alimtvnetwork/gitmap-v28/cli/apperror"
	"github.com/alimtvnetwork/gitmap-v28/cli/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/cli/repodb/enums"
)

// ScanRepoFile maps a database row scanner to a RepoFile entity.
func ScanRepoFile(row dbengine.RowScanner) (*RepoFile, error) {
	var item RepoFile
	var (
		raw_RepoFileId   any
		raw_RelativePath any
		raw_AbsolutePath any
		raw_Content      any
		raw_IsBig        any
		raw_WriteTime    any
		raw_CreatedAt    any
		raw_UpdatedAt    any
	)
	err := row.Scan(
		&raw_RepoFileId,
		&raw_RelativePath,
		&raw_AbsolutePath,
		&raw_Content,
		&raw_IsBig,
		&raw_WriteTime,
		&raw_CreatedAt,
		&raw_UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.RepoFileId = dbengine.ScanUint64(raw_RepoFileId)
	item.RelativePath = dbengine.ScanString(raw_RelativePath)
	item.AbsolutePath = dbengine.ScanString(raw_AbsolutePath)
	item.Content = dbengine.ScanString(raw_Content)
	item.IsBig = dbengine.ScanBool(raw_IsBig)
	item.WriteTime = dbengine.ScanInt64(raw_WriteTime)
	item.CreatedAt = dbengine.ScanInt64(raw_CreatedAt)
	item.UpdatedAt = dbengine.ScanInt64(raw_UpdatedAt)

	return &item, nil
}

// RepoFileDbRepo provides typed database repository access for RepoFile.
type RepoFileDbRepo struct {
	db   *dbengine.DbWrapper
	repo *RepoFileRepository
}

// NewRepoFileDbRepo initializes a typed repository for RepoFile.
func NewRepoFileDbRepo(db *dbengine.DbWrapper) *RepoFileDbRepo {
	repo := dbengine.NewRepository[RepoFile, enums.RepoFileFieldType](
		db,
		enums.RepoFileTable,
		ScanRepoFile,
	)

	return &RepoFileDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *RepoFileDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *RepoFileDbRepo) Repo() *RepoFileRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *RepoFileDbRepo) Query() *RepoFileQueryBuilder {
	return r.repo.Query().Select(enums.RepoFileDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *RepoFileDbRepo) QueryBare() *RepoFileQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *RepoFileDbRepo) FindAll(ctx context.Context) dbengine.ListResult[RepoFile] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *RepoFileDbRepo) First(ctx context.Context) dbengine.EntityResult[RepoFile] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *RepoFileDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

func resolveInsertId(id uint64) any {
	if id == 0 {
		return nil
	}

	return id
}

func checkFileUniqueInDb(ctx context.Context, db *dbengine.DbWrapper, relPath string) *apperror.AppError {
	if db == nil || db.Conn() == nil {
		return nil
	}

	isUnique, err := EnsureFileUniqueInDB(ctx, db.Conn(), relPath)
	if err != nil {
		return apperror.WrapSimple(err, "check file unique")
	}

	if isUnique {
		return nil
	}

	return apperror.New("RepoFileDbRepo.Insert", "E_DUPLICATE_FILE", map[string]any{
		"relativePath": relPath,
	})
}

// Insert inserts a new RepoFile record into the database, verifying path uniqueness.
func (r *RepoFileDbRepo) Insert(ctx context.Context, item *RepoFile) dbengine.RowsAffectedResult {
	if checkErr := checkFileUniqueInDb(ctx, r.db, item.RelativePath); checkErr != nil {
		return dbengine.FailureRowsAffected(checkErr)
	}

	query := "INSERT INTO RepoFile (RepoFileId, RelativePath, AbsolutePath, Content, IsBig, WriteTime, CreatedAt, UpdatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?);"
	id := resolveInsertId(item.RepoFileId)

	return r.db.ExecRowsAffected(ctx, query, id, item.RelativePath, item.AbsolutePath, item.Content, item.IsBig, item.WriteTime, item.CreatedAt, item.UpdatedAt)
}

const sqlRepoFileUpsert = `INSERT INTO RepoFile (
	RelativePath, AbsolutePath, Content, IsBig, WriteTime, CreatedAt, UpdatedAt
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(RelativePath) DO UPDATE SET
	AbsolutePath = excluded.AbsolutePath,
	Content      = excluded.Content,
	IsBig        = excluded.IsBig,
	WriteTime    = excluded.WriteTime,
	UpdatedAt    = excluded.UpdatedAt;`

func resolveCreatedAt(createdAt, now int64) int64 {
	if createdAt == 0 {
		return now
	}

	return createdAt
}

// Upsert inserts a new RepoFile record or updates existing content on RelativePath conflict.
func (r *RepoFileDbRepo) Upsert(ctx context.Context, item *RepoFile) dbengine.RowsAffectedResult {
	now := time.Now().Unix()
	createdAt := resolveCreatedAt(item.CreatedAt, now)

	return r.db.ExecRowsAffected(
		ctx, sqlRepoFileUpsert,
		item.RelativePath, item.AbsolutePath, item.Content,
		item.IsBig, item.WriteTime, createdAt, now,
	)
}

// Update updates an existing RepoFile record identified by its primary key.
func (r *RepoFileDbRepo) Update(ctx context.Context, item *RepoFile) dbengine.RowsAffectedResult {
	query := "UPDATE RepoFile SET RelativePath = ?, AbsolutePath = ?, Content = ?, IsBig = ?, WriteTime = ?, CreatedAt = ?, UpdatedAt = ? WHERE RepoFileId = ?;"

	return r.db.ExecRowsAffected(ctx, query, item.RelativePath, item.AbsolutePath, item.Content, item.IsBig, item.WriteTime, item.CreatedAt, item.UpdatedAt, item.RepoFileId)
}

// DeleteById deletes a RepoFile record by its primary key identifier.
func (r *RepoFileDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.RepoFileDb.RepoFileId, id)
}

func getFileUniqueQuery() string {
	if runtime.GOOS == "windows" {
		return "SELECT COUNT(*) FROM RepoFile WHERE RelativePath = ? COLLATE NOCASE"
	}

	return "SELECT COUNT(*) FROM RepoFile WHERE RelativePath = ?"
}

// EnsureFileUniqueInDB checks if a relative file path is unique in the repository database.
func EnsureFileUniqueInDB(ctx context.Context, db *sql.DB, relPath string) (bool, error) {
	query := getFileUniqueQuery()
	var count int

	if err := db.QueryRowContext(ctx, query, relPath).Scan(&count); err != nil {
		return false, apperror.WrapSimple(err, "EnsureFileUniqueInDB")
	}

	isUnique := count == 0

	return isUnique, nil
}
