// Code generated by gitmap db generate. DO NOT EDIT.

package repodb

import (
	"context"

	"github.com/alimtvnetwork/gitmap-v28/cli/dbengine"
	"github.com/alimtvnetwork/gitmap-v28/cli/repodb/enums"
)

// ScanSearchCache maps a database row scanner to a SearchCache entity.
func ScanSearchCache(row dbengine.RowScanner) (*SearchCache, error) {
	var item SearchCache
	var (
		raw_SearchCacheId any
		raw_Query         any
		raw_Hits          any
		raw_ResultJson    any
		raw_CreatedAt     any
		raw_UpdatedAt     any
	)
	err := row.Scan(
		&raw_SearchCacheId,
		&raw_Query,
		&raw_Hits,
		&raw_ResultJson,
		&raw_CreatedAt,
		&raw_UpdatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.SearchCacheId = dbengine.ScanUint64(raw_SearchCacheId)
	item.Query = dbengine.ScanString(raw_Query)
	item.Hits = dbengine.ScanInt(raw_Hits)
	item.ResultJson = dbengine.ScanString(raw_ResultJson)
	item.CreatedAt = dbengine.ScanInt64(raw_CreatedAt)
	item.UpdatedAt = dbengine.ScanInt64(raw_UpdatedAt)

	return &item, nil
}

// SearchCacheDbRepo provides typed database repository access for SearchCache.
type SearchCacheDbRepo struct {
	db   *dbengine.DbWrapper
	repo *SearchCacheRepository
}

// NewSearchCacheDbRepo initializes a typed repository for SearchCache.
func NewSearchCacheDbRepo(db *dbengine.DbWrapper) *SearchCacheDbRepo {
	repo := dbengine.NewRepository[SearchCache, enums.SearchCacheFieldType](
		db,
		enums.SearchCacheTable,
		ScanSearchCache,
	)

	return &SearchCacheDbRepo{
		db:   db,
		repo: repo,
	}
}

// Db returns the underlying DbWrapper.
func (r *SearchCacheDbRepo) Db() *dbengine.DbWrapper {
	return r.db
}

// Repo returns the underlying generic Repository.
func (r *SearchCacheDbRepo) Repo() *SearchCacheRepository {
	return r.repo
}

// Query returns a fluent QueryBuilder initialized with all standard fields projected.
func (r *SearchCacheDbRepo) Query() *SearchCacheQueryBuilder {
	return r.repo.Query().Select(enums.SearchCacheDb.All()...)
}

// QueryBare returns a fluent QueryBuilder without any pre-selected fields.
func (r *SearchCacheDbRepo) QueryBare() *SearchCacheQueryBuilder {
	return r.repo.Query()
}

// FindAll executes the query selecting all fields and returns a ListResult envelope.
func (r *SearchCacheDbRepo) FindAll(ctx context.Context) dbengine.ListResult[SearchCache] {
	return r.Query().FindAll(ctx)
}

// First executes the query selecting all fields and returns the first record in an EntityResult envelope.
func (r *SearchCacheDbRepo) First(ctx context.Context) dbengine.EntityResult[SearchCache] {
	return r.Query().First(ctx)
}

// Count returns the total number of records matching the query.
func (r *SearchCacheDbRepo) Count(ctx context.Context) dbengine.Int64Result {
	return r.Query().Count(ctx)
}

// Insert inserts a new SearchCache record into the database.
func (r *SearchCacheDbRepo) Insert(ctx context.Context, item *SearchCache) dbengine.RowsAffectedResult {
	query := "INSERT INTO SearchCache (SearchCacheId, Query, Hits, ResultJson, CreatedAt, UpdatedAt) VALUES (?, ?, ?, ?, ?, ?);"
	var id any = item.SearchCacheId
	if item.SearchCacheId == 0 {
		id = nil
	}

	return r.db.ExecRowsAffected(ctx, query, id, item.Query, item.Hits, item.ResultJson, item.CreatedAt, item.UpdatedAt)
}

// Update updates an existing SearchCache record identified by its primary key.
func (r *SearchCacheDbRepo) Update(ctx context.Context, item *SearchCache) dbengine.RowsAffectedResult {
	query := "UPDATE SearchCache SET Query = ?, Hits = ?, ResultJson = ?, CreatedAt = ?, UpdatedAt = ? WHERE SearchCacheId = ?;"

	return r.db.ExecRowsAffected(ctx, query, item.Query, item.Hits, item.ResultJson, item.CreatedAt, item.UpdatedAt, item.SearchCacheId)
}

// DeleteById deletes a SearchCache record by its primary key identifier.
func (r *SearchCacheDbRepo) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {
	return r.repo.DeleteBy(ctx, enums.SearchCacheDb.SearchCacheId, id)
}
