// Code generated by gitmap db generate. DO NOT EDIT.

package enums

// Canonical table name constants.
const (
	PipelineDbStatsTable     = "PipelineDbStats"
	PipelineErrorRecordTable = "PipelineErrorRecord"
	PipelineErrorTable       = PipelineErrorRecordTable
	PipelineRunRecordTable   = "PipelineRunRecord"
	PipelineRunTable         = PipelineRunRecordTable
	PipelineSplitDbTable     = "PipelineSplitDb"
)
