// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/apperror"
)

// PipelineDbStatsFieldType represents column name enums for PipelineDbStats.
type PipelineDbStatsFieldType string

// Name returns the identifier name of the field enum.
func (e PipelineDbStatsFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e PipelineDbStatsFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e PipelineDbStatsFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e PipelineDbStatsFieldType) IsCompare(target PipelineDbStatsFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e PipelineDbStatsFieldType) IsEnum() bool {
	return pipelineDbStatsValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e PipelineDbStatsFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *PipelineDbStatsFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	target := PipelineDbStatsFieldType(s)
	if !pipelineDbStatsValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "PipelineDbStatsFieldType", s)
	}
	*e = target
	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e PipelineDbStatsFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}
	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *PipelineDbStatsFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}
	target := PipelineDbStatsFieldType(str)
	if !pipelineDbStatsValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "PipelineDbStatsFieldType", str), "validate field enum from json")
	}
	*e = target
	return nil
}

// IsPath checks whether this field enum instance is Path.
func (e PipelineDbStatsFieldType) IsPath() bool {
	return e == PipelineDbStatsDb.Path
}

// IsSize checks whether this field enum instance is Size.
func (e PipelineDbStatsFieldType) IsSize() bool {
	return e == PipelineDbStatsDb.Size
}

// IsTotalRuns checks whether this field enum instance is TotalRuns.
func (e PipelineDbStatsFieldType) IsTotalRuns() bool {
	return e == PipelineDbStatsDb.TotalRuns
}

// IsSuccessRuns checks whether this field enum instance is SuccessRuns.
func (e PipelineDbStatsFieldType) IsSuccessRuns() bool {
	return e == PipelineDbStatsDb.SuccessRuns
}

// IsFailedRuns checks whether this field enum instance is FailedRuns.
func (e PipelineDbStatsFieldType) IsFailedRuns() bool {
	return e == PipelineDbStatsDb.FailedRuns
}

// IsErrorLogCount checks whether this field enum instance is ErrorLogCount.
func (e PipelineDbStatsFieldType) IsErrorLogCount() bool {
	return e == PipelineDbStatsDb.ErrorLogCount
}

// IsSegmentCount checks whether this field enum instance is SegmentCount.
func (e PipelineDbStatsFieldType) IsSegmentCount() bool {
	return e == PipelineDbStatsDb.SegmentCount
}

// IsLastUpdated checks whether this field enum instance is LastUpdated.
func (e PipelineDbStatsFieldType) IsLastUpdated() bool {
	return e == PipelineDbStatsDb.LastUpdated
}

type pipelineDbStatsDbRegistry struct {
	Path          PipelineDbStatsFieldType
	Size          PipelineDbStatsFieldType
	TotalRuns     PipelineDbStatsFieldType
	SuccessRuns   PipelineDbStatsFieldType
	FailedRuns    PipelineDbStatsFieldType
	ErrorLogCount PipelineDbStatsFieldType
	SegmentCount  PipelineDbStatsFieldType
	LastUpdated   PipelineDbStatsFieldType
}

// All returns a slice of all field enums in PipelineDbStats.
func (r pipelineDbStatsDbRegistry) All() []PipelineDbStatsFieldType {
	return []PipelineDbStatsFieldType{
		r.Path,
		r.Size,
		r.TotalRuns,
		r.SuccessRuns,
		r.FailedRuns,
		r.ErrorLogCount,
		r.SegmentCount,
		r.LastUpdated,
	}
}

// Names returns a slice of string names for all fields in PipelineDbStats.
func (r pipelineDbStatsDbRegistry) Names() []string {
	return []string{
		"Path",
		"Size",
		"TotalRuns",
		"SuccessRuns",
		"FailedRuns",
		"ErrorLogCount",
		"SegmentCount",
		"LastUpdated",
	}
}

// IsEnum checks whether the target object matches any registered field enum in PipelineDbStats.
func (r pipelineDbStatsDbRegistry) IsEnum(target PipelineDbStatsFieldType) bool {
	return pipelineDbStatsValidMap[target]
}

// IsPath checks whether the target object is Path.
func (r pipelineDbStatsDbRegistry) IsPath(target PipelineDbStatsFieldType) bool {
	return target == r.Path
}

// IsSize checks whether the target object is Size.
func (r pipelineDbStatsDbRegistry) IsSize(target PipelineDbStatsFieldType) bool {
	return target == r.Size
}

// IsTotalRuns checks whether the target object is TotalRuns.
func (r pipelineDbStatsDbRegistry) IsTotalRuns(target PipelineDbStatsFieldType) bool {
	return target == r.TotalRuns
}

// IsSuccessRuns checks whether the target object is SuccessRuns.
func (r pipelineDbStatsDbRegistry) IsSuccessRuns(target PipelineDbStatsFieldType) bool {
	return target == r.SuccessRuns
}

// IsFailedRuns checks whether the target object is FailedRuns.
func (r pipelineDbStatsDbRegistry) IsFailedRuns(target PipelineDbStatsFieldType) bool {
	return target == r.FailedRuns
}

// IsErrorLogCount checks whether the target object is ErrorLogCount.
func (r pipelineDbStatsDbRegistry) IsErrorLogCount(target PipelineDbStatsFieldType) bool {
	return target == r.ErrorLogCount
}

// IsSegmentCount checks whether the target object is SegmentCount.
func (r pipelineDbStatsDbRegistry) IsSegmentCount(target PipelineDbStatsFieldType) bool {
	return target == r.SegmentCount
}

// IsLastUpdated checks whether the target object is LastUpdated.
func (r pipelineDbStatsDbRegistry) IsLastUpdated(target PipelineDbStatsFieldType) bool {
	return target == r.LastUpdated
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r pipelineDbStatsDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}
	return string(b), nil
}

// PipelineDbStatsDb provides scoped access to field enums: PipelineDbStatsDb.<Field>.
var PipelineDbStatsDb = pipelineDbStatsDbRegistry{
	Path:          "Path",
	Size:          "Size",
	TotalRuns:     "TotalRuns",
	SuccessRuns:   "SuccessRuns",
	FailedRuns:    "FailedRuns",
	ErrorLogCount: "ErrorLogCount",
	SegmentCount:  "SegmentCount",
	LastUpdated:   "LastUpdated",
}

// pipelineDbStatsValidMap provides O(1) map validation for field enums.
var pipelineDbStatsValidMap = map[PipelineDbStatsFieldType]bool{
	PipelineDbStatsDb.Path:          true,
	PipelineDbStatsDb.Size:          true,
	PipelineDbStatsDb.TotalRuns:     true,
	PipelineDbStatsDb.SuccessRuns:   true,
	PipelineDbStatsDb.FailedRuns:    true,
	PipelineDbStatsDb.ErrorLogCount: true,
	PipelineDbStatsDb.SegmentCount:  true,
	PipelineDbStatsDb.LastUpdated:   true,
}

// PipelineDbStatsField is an alias to PipelineDbStatsDb.
var PipelineDbStatsField = PipelineDbStatsDb
