// Code generated by gitmap db generate. DO NOT EDIT.

package enums

// Canonical table name constants.
const (
	RepoFileTable        = "RepoFile"
	SearchCacheTable     = "SearchCache"
	FileSequenceTable    = "FileSequence"
	SequenceHistoryTable = "SequenceHistory"
	RepoScanLogTable     = "RepoScanLog"
	IndexedRepoTable     = "IndexedRepo"
)
