// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/apperror"
)

// FileSequenceFieldType represents column name enums for FileSequence.
type FileSequenceFieldType string

// Name returns the identifier name of the field enum.
func (e FileSequenceFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e FileSequenceFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e FileSequenceFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e FileSequenceFieldType) IsCompare(target FileSequenceFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e FileSequenceFieldType) IsEnum() bool {
	return fileSequenceValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e FileSequenceFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *FileSequenceFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	target := FileSequenceFieldType(s)
	if !fileSequenceValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "FileSequenceFieldType", s)
	}
	*e = target
	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e FileSequenceFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}
	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *FileSequenceFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}
	target := FileSequenceFieldType(str)
	if !fileSequenceValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "FileSequenceFieldType", str), "validate field enum from json")
	}
	*e = target
	return nil
}

// IsFileSequenceId checks whether this field enum instance is FileSequenceId.
func (e FileSequenceFieldType) IsFileSequenceId() bool {
	return e == FileSequenceDb.FileSequenceId
}

// IsDirectory checks whether this field enum instance is Directory.
func (e FileSequenceFieldType) IsDirectory() bool {
	return e == FileSequenceDb.Directory
}

// IsFilename checks whether this field enum instance is Filename.
func (e FileSequenceFieldType) IsFilename() bool {
	return e == FileSequenceDb.Filename
}

// IsSequenceNumber checks whether this field enum instance is SequenceNumber.
func (e FileSequenceFieldType) IsSequenceNumber() bool {
	return e == FileSequenceDb.SequenceNumber
}

// IsBaseName checks whether this field enum instance is BaseName.
func (e FileSequenceFieldType) IsBaseName() bool {
	return e == FileSequenceDb.BaseName
}

// IsUpdatedAt checks whether this field enum instance is UpdatedAt.
func (e FileSequenceFieldType) IsUpdatedAt() bool {
	return e == FileSequenceDb.UpdatedAt
}

type fileSequenceDbRegistry struct {
	FileSequenceId FileSequenceFieldType
	Directory      FileSequenceFieldType
	Filename       FileSequenceFieldType
	SequenceNumber FileSequenceFieldType
	BaseName       FileSequenceFieldType
	UpdatedAt      FileSequenceFieldType
}

// All returns a slice of all field enums in FileSequence.
func (r fileSequenceDbRegistry) All() []FileSequenceFieldType {
	return []FileSequenceFieldType{
		r.FileSequenceId,
		r.Directory,
		r.Filename,
		r.SequenceNumber,
		r.BaseName,
		r.UpdatedAt,
	}
}

// Names returns a slice of string names for all fields in FileSequence.
func (r fileSequenceDbRegistry) Names() []string {
	return []string{
		"FileSequenceId",
		"Directory",
		"Filename",
		"SequenceNumber",
		"BaseName",
		"UpdatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in FileSequence.
func (r fileSequenceDbRegistry) IsEnum(target FileSequenceFieldType) bool {
	return fileSequenceValidMap[target]
}

// IsFileSequenceId checks whether the target object is FileSequenceId.
func (r fileSequenceDbRegistry) IsFileSequenceId(target FileSequenceFieldType) bool {
	return target == r.FileSequenceId
}

// IsDirectory checks whether the target object is Directory.
func (r fileSequenceDbRegistry) IsDirectory(target FileSequenceFieldType) bool {
	return target == r.Directory
}

// IsFilename checks whether the target object is Filename.
func (r fileSequenceDbRegistry) IsFilename(target FileSequenceFieldType) bool {
	return target == r.Filename
}

// IsSequenceNumber checks whether the target object is SequenceNumber.
func (r fileSequenceDbRegistry) IsSequenceNumber(target FileSequenceFieldType) bool {
	return target == r.SequenceNumber
}

// IsBaseName checks whether the target object is BaseName.
func (r fileSequenceDbRegistry) IsBaseName(target FileSequenceFieldType) bool {
	return target == r.BaseName
}

// IsUpdatedAt checks whether the target object is UpdatedAt.
func (r fileSequenceDbRegistry) IsUpdatedAt(target FileSequenceFieldType) bool {
	return target == r.UpdatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r fileSequenceDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}
	return string(b), nil
}

// FileSequenceDb provides scoped access to field enums: FileSequenceDb.<Field>.
var FileSequenceDb = fileSequenceDbRegistry{
	FileSequenceId: "FileSequenceId",
	Directory:      "Directory",
	Filename:       "Filename",
	SequenceNumber: "SequenceNumber",
	BaseName:       "BaseName",
	UpdatedAt:      "UpdatedAt",
}

// fileSequenceValidMap provides O(1) map validation for field enums.
var fileSequenceValidMap = map[FileSequenceFieldType]bool{
	FileSequenceDb.FileSequenceId: true,
	FileSequenceDb.Directory:      true,
	FileSequenceDb.Filename:       true,
	FileSequenceDb.SequenceNumber: true,
	FileSequenceDb.BaseName:       true,
	FileSequenceDb.UpdatedAt:      true,
}

// FileSequenceField is an alias to FileSequenceDb.
var FileSequenceField = FileSequenceDb
