// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/apperror"
)

// IndexedRepoFieldType represents column name enums for IndexedRepo.
type IndexedRepoFieldType string

// Name returns the identifier name of the field enum.
func (e IndexedRepoFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e IndexedRepoFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e IndexedRepoFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e IndexedRepoFieldType) IsCompare(target IndexedRepoFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e IndexedRepoFieldType) IsEnum() bool {
	return indexedRepoValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e IndexedRepoFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *IndexedRepoFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	target := IndexedRepoFieldType(s)
	if !indexedRepoValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "IndexedRepoFieldType", s)
	}
	*e = target
	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e IndexedRepoFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}
	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *IndexedRepoFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}
	target := IndexedRepoFieldType(str)
	if !indexedRepoValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "IndexedRepoFieldType", str), "validate field enum from json")
	}
	*e = target
	return nil
}

// IsIndexedRepoId checks whether this field enum instance is IndexedRepoId.
func (e IndexedRepoFieldType) IsIndexedRepoId() bool {
	return e == IndexedRepoDb.IndexedRepoId
}

// IsPath checks whether this field enum instance is Path.
func (e IndexedRepoFieldType) IsPath() bool {
	return e == IndexedRepoDb.Path
}

// IsSlug checks whether this field enum instance is Slug.
func (e IndexedRepoFieldType) IsSlug() bool {
	return e == IndexedRepoDb.Slug
}

// IsMigratedVersion checks whether this field enum instance is MigratedVersion.
func (e IndexedRepoFieldType) IsMigratedVersion() bool {
	return e == IndexedRepoDb.MigratedVersion
}

// IsCreatedAt checks whether this field enum instance is CreatedAt.
func (e IndexedRepoFieldType) IsCreatedAt() bool {
	return e == IndexedRepoDb.CreatedAt
}

// IsUpdatedAt checks whether this field enum instance is UpdatedAt.
func (e IndexedRepoFieldType) IsUpdatedAt() bool {
	return e == IndexedRepoDb.UpdatedAt
}

type indexedRepoDbRegistry struct {
	IndexedRepoId   IndexedRepoFieldType
	Path            IndexedRepoFieldType
	Slug            IndexedRepoFieldType
	MigratedVersion IndexedRepoFieldType
	CreatedAt       IndexedRepoFieldType
	UpdatedAt       IndexedRepoFieldType
}

// All returns a slice of all field enums in IndexedRepo.
func (r indexedRepoDbRegistry) All() []IndexedRepoFieldType {
	return []IndexedRepoFieldType{
		r.IndexedRepoId,
		r.Path,
		r.Slug,
		r.MigratedVersion,
		r.CreatedAt,
		r.UpdatedAt,
	}
}

// Names returns a slice of string names for all fields in IndexedRepo.
func (r indexedRepoDbRegistry) Names() []string {
	return []string{
		"IndexedRepoId",
		"Path",
		"Slug",
		"MigratedVersion",
		"CreatedAt",
		"UpdatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in IndexedRepo.
func (r indexedRepoDbRegistry) IsEnum(target IndexedRepoFieldType) bool {
	return indexedRepoValidMap[target]
}

// IsIndexedRepoId checks whether the target object is IndexedRepoId.
func (r indexedRepoDbRegistry) IsIndexedRepoId(target IndexedRepoFieldType) bool {
	return target == r.IndexedRepoId
}

// IsPath checks whether the target object is Path.
func (r indexedRepoDbRegistry) IsPath(target IndexedRepoFieldType) bool {
	return target == r.Path
}

// IsSlug checks whether the target object is Slug.
func (r indexedRepoDbRegistry) IsSlug(target IndexedRepoFieldType) bool {
	return target == r.Slug
}

// IsMigratedVersion checks whether the target object is MigratedVersion.
func (r indexedRepoDbRegistry) IsMigratedVersion(target IndexedRepoFieldType) bool {
	return target == r.MigratedVersion
}

// IsCreatedAt checks whether the target object is CreatedAt.
func (r indexedRepoDbRegistry) IsCreatedAt(target IndexedRepoFieldType) bool {
	return target == r.CreatedAt
}

// IsUpdatedAt checks whether the target object is UpdatedAt.
func (r indexedRepoDbRegistry) IsUpdatedAt(target IndexedRepoFieldType) bool {
	return target == r.UpdatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r indexedRepoDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}
	return string(b), nil
}

// IndexedRepoDb provides scoped access to field enums: IndexedRepoDb.<Field>.
var IndexedRepoDb = indexedRepoDbRegistry{
	IndexedRepoId:   "IndexedRepoId",
	Path:            "Path",
	Slug:            "Slug",
	MigratedVersion: "MigratedVersion",
	CreatedAt:       "CreatedAt",
	UpdatedAt:       "UpdatedAt",
}

// indexedRepoValidMap provides O(1) map validation for field enums.
var indexedRepoValidMap = map[IndexedRepoFieldType]bool{
	IndexedRepoDb.IndexedRepoId:   true,
	IndexedRepoDb.Path:            true,
	IndexedRepoDb.Slug:            true,
	IndexedRepoDb.MigratedVersion: true,
	IndexedRepoDb.CreatedAt:       true,
	IndexedRepoDb.UpdatedAt:       true,
}

// IndexedRepoField is an alias to IndexedRepoDb.
var IndexedRepoField = IndexedRepoDb
