// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/apperror"
)

// RepoScanLogFieldType represents column name enums for RepoScanLog.
type RepoScanLogFieldType string

// Name returns the identifier name of the field enum.
func (e RepoScanLogFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e RepoScanLogFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e RepoScanLogFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e RepoScanLogFieldType) IsCompare(target RepoScanLogFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e RepoScanLogFieldType) IsEnum() bool {
	return repoScanLogValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e RepoScanLogFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *RepoScanLogFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	target := RepoScanLogFieldType(s)
	if !repoScanLogValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "RepoScanLogFieldType", s)
	}
	*e = target
	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e RepoScanLogFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}
	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *RepoScanLogFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}
	target := RepoScanLogFieldType(str)
	if !repoScanLogValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "RepoScanLogFieldType", str), "validate field enum from json")
	}
	*e = target
	return nil
}

// IsRepoScanLogId checks whether this field enum instance is RepoScanLogId.
func (e RepoScanLogFieldType) IsRepoScanLogId() bool {
	return e == RepoScanLogDb.RepoScanLogId
}

// IsRepoId checks whether this field enum instance is RepoId.
func (e RepoScanLogFieldType) IsRepoId() bool {
	return e == RepoScanLogDb.RepoId
}

// IsRepoSlug checks whether this field enum instance is RepoSlug.
func (e RepoScanLogFieldType) IsRepoSlug() bool {
	return e == RepoScanLogDb.RepoSlug
}

// IsAction checks whether this field enum instance is Action.
func (e RepoScanLogFieldType) IsAction() bool {
	return e == RepoScanLogDb.Action
}

// IsStatus checks whether this field enum instance is Status.
func (e RepoScanLogFieldType) IsStatus() bool {
	return e == RepoScanLogDb.Status
}

// IsErrorMessage checks whether this field enum instance is ErrorMessage.
func (e RepoScanLogFieldType) IsErrorMessage() bool {
	return e == RepoScanLogDb.ErrorMessage
}

// IsDetails checks whether this field enum instance is Details.
func (e RepoScanLogFieldType) IsDetails() bool {
	return e == RepoScanLogDb.Details
}

// IsNotes checks whether this field enum instance is Notes.
func (e RepoScanLogFieldType) IsNotes() bool {
	return e == RepoScanLogDb.Notes
}

// IsComments checks whether this field enum instance is Comments.
func (e RepoScanLogFieldType) IsComments() bool {
	return e == RepoScanLogDb.Comments
}

// IsCreatedAt checks whether this field enum instance is CreatedAt.
func (e RepoScanLogFieldType) IsCreatedAt() bool {
	return e == RepoScanLogDb.CreatedAt
}

type repoScanLogDbRegistry struct {
	RepoScanLogId RepoScanLogFieldType
	RepoId        RepoScanLogFieldType
	RepoSlug      RepoScanLogFieldType
	Action        RepoScanLogFieldType
	Status        RepoScanLogFieldType
	ErrorMessage  RepoScanLogFieldType
	Details       RepoScanLogFieldType
	Notes         RepoScanLogFieldType
	Comments      RepoScanLogFieldType
	CreatedAt     RepoScanLogFieldType
}

// All returns a slice of all field enums in RepoScanLog.
func (r repoScanLogDbRegistry) All() []RepoScanLogFieldType {
	return []RepoScanLogFieldType{
		r.RepoScanLogId,
		r.RepoId,
		r.RepoSlug,
		r.Action,
		r.Status,
		r.ErrorMessage,
		r.Details,
		r.Notes,
		r.Comments,
		r.CreatedAt,
	}
}

// Names returns a slice of string names for all fields in RepoScanLog.
func (r repoScanLogDbRegistry) Names() []string {
	return []string{
		"RepoScanLogId",
		"RepoId",
		"RepoSlug",
		"Action",
		"Status",
		"ErrorMessage",
		"Details",
		"Notes",
		"Comments",
		"CreatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in RepoScanLog.
func (r repoScanLogDbRegistry) IsEnum(target RepoScanLogFieldType) bool {
	return repoScanLogValidMap[target]
}

// IsRepoScanLogId checks whether the target object is RepoScanLogId.
func (r repoScanLogDbRegistry) IsRepoScanLogId(target RepoScanLogFieldType) bool {
	return target == r.RepoScanLogId
}

// IsRepoId checks whether the target object is RepoId.
func (r repoScanLogDbRegistry) IsRepoId(target RepoScanLogFieldType) bool {
	return target == r.RepoId
}

// IsRepoSlug checks whether the target object is RepoSlug.
func (r repoScanLogDbRegistry) IsRepoSlug(target RepoScanLogFieldType) bool {
	return target == r.RepoSlug
}

// IsAction checks whether the target object is Action.
func (r repoScanLogDbRegistry) IsAction(target RepoScanLogFieldType) bool {
	return target == r.Action
}

// IsStatus checks whether the target object is Status.
func (r repoScanLogDbRegistry) IsStatus(target RepoScanLogFieldType) bool {
	return target == r.Status
}

// IsErrorMessage checks whether the target object is ErrorMessage.
func (r repoScanLogDbRegistry) IsErrorMessage(target RepoScanLogFieldType) bool {
	return target == r.ErrorMessage
}

// IsDetails checks whether the target object is Details.
func (r repoScanLogDbRegistry) IsDetails(target RepoScanLogFieldType) bool {
	return target == r.Details
}

// IsNotes checks whether the target object is Notes.
func (r repoScanLogDbRegistry) IsNotes(target RepoScanLogFieldType) bool {
	return target == r.Notes
}

// IsComments checks whether the target object is Comments.
func (r repoScanLogDbRegistry) IsComments(target RepoScanLogFieldType) bool {
	return target == r.Comments
}

// IsCreatedAt checks whether the target object is CreatedAt.
func (r repoScanLogDbRegistry) IsCreatedAt(target RepoScanLogFieldType) bool {
	return target == r.CreatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r repoScanLogDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}
	return string(b), nil
}

// RepoScanLogDb provides scoped access to field enums: RepoScanLogDb.<Field>.
var RepoScanLogDb = repoScanLogDbRegistry{
	RepoScanLogId: "RepoScanLogId",
	RepoId:        "RepoId",
	RepoSlug:      "RepoSlug",
	Action:        "Action",
	Status:        "Status",
	ErrorMessage:  "ErrorMessage",
	Details:       "Details",
	Notes:         "Notes",
	Comments:      "Comments",
	CreatedAt:     "CreatedAt",
}

// repoScanLogValidMap provides O(1) map validation for field enums.
var repoScanLogValidMap = map[RepoScanLogFieldType]bool{
	RepoScanLogDb.RepoScanLogId: true,
	RepoScanLogDb.RepoId:        true,
	RepoScanLogDb.RepoSlug:      true,
	RepoScanLogDb.Action:        true,
	RepoScanLogDb.Status:        true,
	RepoScanLogDb.ErrorMessage:  true,
	RepoScanLogDb.Details:       true,
	RepoScanLogDb.Notes:         true,
	RepoScanLogDb.Comments:      true,
	RepoScanLogDb.CreatedAt:     true,
}

// RepoScanLogField is an alias to RepoScanLogDb.
var RepoScanLogField = RepoScanLogDb
