// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/gitmap/apperror"
)

// SequenceHistoryFieldType represents column name enums for SequenceHistory.
type SequenceHistoryFieldType string

// Name returns the identifier name of the field enum.
func (e SequenceHistoryFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e SequenceHistoryFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e SequenceHistoryFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e SequenceHistoryFieldType) IsCompare(target SequenceHistoryFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e SequenceHistoryFieldType) IsEnum() bool {
	return sequenceHistoryValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e SequenceHistoryFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *SequenceHistoryFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	target := SequenceHistoryFieldType(s)
	if !sequenceHistoryValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "SequenceHistoryFieldType", s)
	}

	*e = target

	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e SequenceHistoryFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}

	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *SequenceHistoryFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}

	target := SequenceHistoryFieldType(str)
	if !sequenceHistoryValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "SequenceHistoryFieldType", str), "validate field enum from json")
	}

	*e = target

	return nil
}

// IsSequenceHistoryId checks whether this field enum instance is SequenceHistoryId.
func (e SequenceHistoryFieldType) IsSequenceHistoryId() bool {
	return e == SequenceHistoryDb.SequenceHistoryId
}

// IsDirectory checks whether this field enum instance is Directory.
func (e SequenceHistoryFieldType) IsDirectory() bool {
	return e == SequenceHistoryDb.Directory
}

// IsOperationsJson checks whether this field enum instance is OperationsJson.
func (e SequenceHistoryFieldType) IsOperationsJson() bool {
	return e == SequenceHistoryDb.OperationsJson
}

// IsCreatedAt checks whether this field enum instance is CreatedAt.
func (e SequenceHistoryFieldType) IsCreatedAt() bool {
	return e == SequenceHistoryDb.CreatedAt
}

type sequenceHistoryDbRegistry struct {
	SequenceHistoryId SequenceHistoryFieldType
	Directory         SequenceHistoryFieldType
	OperationsJson    SequenceHistoryFieldType
	CreatedAt         SequenceHistoryFieldType
}

// All returns a slice of all field enums in SequenceHistory.
func (r sequenceHistoryDbRegistry) All() []SequenceHistoryFieldType {
	return []SequenceHistoryFieldType{
		r.SequenceHistoryId,
		r.Directory,
		r.OperationsJson,
		r.CreatedAt,
	}
}

// Names returns a slice of string names for all fields in SequenceHistory.
func (r sequenceHistoryDbRegistry) Names() []string {
	return []string{
		"SequenceHistoryId",
		"Directory",
		"OperationsJson",
		"CreatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in SequenceHistory.
func (r sequenceHistoryDbRegistry) IsEnum(target SequenceHistoryFieldType) bool {
	return sequenceHistoryValidMap[target]
}

// IsSequenceHistoryId checks whether the target object is SequenceHistoryId.
func (r sequenceHistoryDbRegistry) IsSequenceHistoryId(target SequenceHistoryFieldType) bool {
	return target == r.SequenceHistoryId
}

// IsDirectory checks whether the target object is Directory.
func (r sequenceHistoryDbRegistry) IsDirectory(target SequenceHistoryFieldType) bool {
	return target == r.Directory
}

// IsOperationsJson checks whether the target object is OperationsJson.
func (r sequenceHistoryDbRegistry) IsOperationsJson(target SequenceHistoryFieldType) bool {
	return target == r.OperationsJson
}

// IsCreatedAt checks whether the target object is CreatedAt.
func (r sequenceHistoryDbRegistry) IsCreatedAt(target SequenceHistoryFieldType) bool {
	return target == r.CreatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r sequenceHistoryDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}

	return string(b), nil
}

// SequenceHistoryDb provides scoped access to field enums: SequenceHistoryDb.<Field>.
var SequenceHistoryDb = sequenceHistoryDbRegistry{
	SequenceHistoryId: "SequenceHistoryId",
	Directory:         "Directory",
	OperationsJson:    "OperationsJson",
	CreatedAt:         "CreatedAt",
}

// sequenceHistoryValidMap provides O(1) map validation for field enums.
var sequenceHistoryValidMap = map[SequenceHistoryFieldType]bool{
	SequenceHistoryDb.SequenceHistoryId: true,
	SequenceHistoryDb.Directory:         true,
	SequenceHistoryDb.OperationsJson:    true,
	SequenceHistoryDb.CreatedAt:         true,
}

// SequenceHistoryField is an alias to SequenceHistoryDb.
var SequenceHistoryField = SequenceHistoryDb
