#!/usr/bin/env python3
"""
30-db-struct-enum-generator.py — Inspects Go model structs and auto-generates type-safe column enums.

Usage:
  python 03-ai-scripts/30-db-struct-enum-generator.py --dir gitmap/store
  python 03-ai-scripts/30-db-struct-enum-generator.py --file gitmap/pipelinedb/pipeline_split_db.go
  python 03-ai-scripts/30-db-struct-enum-generator.py --dry-run
"""

from __future__ import annotations

import argparse
from importlib import import_module
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).parent))
engine = import_module("02-shared-engine")

ExitCodeType = engine.ExitCodeType

STRUCT_PATTERN = re.compile(r'type\s+([A-Za-z0-9_]+)\s+struct\s*\{([^}]+)\}', re.MULTILINE)
FIELD_PATTERN = re.compile(r'^\s*([A-Za-z0-9_]+)\s+([A-Za-z0-9_\[\]*]+)(?:\s+`([^`]+)`)?', re.MULTILINE)
PACKAGE_PATTERN = re.compile(r'package\s+([A-Za-z0-9_]+)')


def parse_structs_from_file(file_path: Path) -> tuple[str, list[dict]]:
    content = file_path.read_text(encoding="utf-8", errors="replace")
    pkg_match = PACKAGE_PATTERN.search(content)
    pkg_name = pkg_match.group(1) if pkg_match else "models"

    structs = []
    for match in STRUCT_PATTERN.finditer(content):
        struct_name = match.group(1)
        body = match.group(2)

        fields = []
        for f_match in FIELD_PATTERN.finditer(body):
            field_name = f_match.group(1)
            field_type = f_match.group(2)
            tags = f_match.group(3) or ""

            # Check if public field and not embedded
            if field_name[0].isupper() and not field_name.startswith("XXX_"):
                fields.append({
                    "name": field_name,
                    "type": field_type,
                    "tags": tags,
                })

        if fields:
            structs.append({
                "name": struct_name,
                "fields": fields,
            })

    return pkg_name, structs


def generate_enums_for_struct(struct_info: dict) -> str:
    s_name = struct_info["name"]
    enum_type = f"{s_name}FieldType"

    lines = [
        f"// {enum_type} represents column name enums for {s_name}.",
        f"type {enum_type} string",
        "",
        "const (",
    ]
    for f in struct_info["fields"]:
        f_name = f["name"]
        const_name = f"{s_name}Field{f_name}"
        lines.append(f'\t{const_name} {enum_type} = "{f_name}"')
    lines.append(")")
    lines.append("")
    lines.append(f"// {s_name}Table represents the canonical table name.")
    lines.append(f'const {s_name}Table = "{s_name}"')
    lines.append("")

    return "\n".join(lines)


def process_target_file(target_file: Path, dry_run: bool = False) -> bool:
    pkg_name, structs = parse_structs_from_file(target_file)
    if not structs:
        return False

    out_file = target_file.parent / f"{target_file.stem}_fields_gen.go"

    header = f"""// Code generated by gitmap db generate. DO NOT EDIT.

package {pkg_name}

"""
    body = "\n".join(generate_enums_for_struct(s) for s in structs)
    full_content = header + body

    if dry_run:
        print(f"[DRY RUN] Would generate: {out_file} ({len(structs)} structs)")
        return True

    out_file.write_text(full_content, encoding="utf-8")
    print(f"  ✔ Generated {out_file.name} ({len(structs)} structs)")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate type-safe column name enums from Go model structs")
    parser.add_argument("--dir", help="Directory containing Go model files", default="")
    parser.add_argument("--file", help="Specific Go model file to parse", default="")
    parser.add_argument("--dry-run", action="store_true", help="Preview output without writing files")

    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parent.parent

    if args.file:
        file_path = Path(args.file)
        if not file_path.is_absolute():
            file_path = repo_root / file_path
        if not file_path.is_file():
            print(f"Error: file not found: {file_path}", file=sys.stderr)
            return 1
        process_target_file(file_path, args.dry_run)
        return 0

    target_dir = Path(args.dir) if args.dir else repo_root / "gitmap" / "pipelinedb"
    if not target_dir.is_absolute():
        target_dir = repo_root / target_dir

    if not target_dir.is_dir():
        print(f"Error: directory not found: {target_dir}", file=sys.stderr)
        return 1

    generated_count = 0
    for go_file in target_dir.glob("*.go"):
        if go_file.name.endswith("_test.go") or go_file.name.endswith("_gen.go"):
            continue
        if process_target_file(go_file, args.dry_run):
            generated_count += 1

    print(f"Completed: processed files in {target_dir} ({generated_count} files generated enums).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
