// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/cli/apperror"
)

// RepoFileFieldType represents column name enums for RepoFile.
type RepoFileFieldType string

// Name returns the identifier name of the field enum.
func (e RepoFileFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e RepoFileFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e RepoFileFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e RepoFileFieldType) IsCompare(target RepoFileFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e RepoFileFieldType) IsEnum() bool {
	return repoFileValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e RepoFileFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *RepoFileFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	target := RepoFileFieldType(s)
	if !repoFileValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "RepoFileFieldType", s)
	}

	*e = target

	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e RepoFileFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}

	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *RepoFileFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}

	target := RepoFileFieldType(str)
	if !repoFileValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "RepoFileFieldType", str), "validate field enum from json")
	}

	*e = target

	return nil
}

// IsRepoFileId checks whether this field enum instance is RepoFileId.
func (e RepoFileFieldType) IsRepoFileId() bool {
	return e == RepoFileDb.RepoFileId
}

// IsRelativePath checks whether this field enum instance is RelativePath.
func (e RepoFileFieldType) IsRelativePath() bool {
	return e == RepoFileDb.RelativePath
}

// IsAbsolutePath checks whether this field enum instance is AbsolutePath.
func (e RepoFileFieldType) IsAbsolutePath() bool {
	return e == RepoFileDb.AbsolutePath
}

// IsContent checks whether this field enum instance is Content.
func (e RepoFileFieldType) IsContent() bool {
	return e == RepoFileDb.Content
}

// IsIsBig checks whether this field enum instance is IsBig.
func (e RepoFileFieldType) IsIsBig() bool {
	return e == RepoFileDb.IsBig
}

// IsWriteTime checks whether this field enum instance is WriteTime.
func (e RepoFileFieldType) IsWriteTime() bool {
	return e == RepoFileDb.WriteTime
}

// IsCreatedAt checks whether this field enum instance is CreatedAt.
func (e RepoFileFieldType) IsCreatedAt() bool {
	return e == RepoFileDb.CreatedAt
}

// IsUpdatedAt checks whether this field enum instance is UpdatedAt.
func (e RepoFileFieldType) IsUpdatedAt() bool {
	return e == RepoFileDb.UpdatedAt
}

type repoFileDbRegistry struct {
	RepoFileId   RepoFileFieldType
	RelativePath RepoFileFieldType
	AbsolutePath RepoFileFieldType
	Content      RepoFileFieldType
	IsBig        RepoFileFieldType
	WriteTime    RepoFileFieldType
	CreatedAt    RepoFileFieldType
	UpdatedAt    RepoFileFieldType
}

// All returns a slice of all field enums in RepoFile.
func (r repoFileDbRegistry) All() []RepoFileFieldType {
	return []RepoFileFieldType{
		r.RepoFileId,
		r.RelativePath,
		r.AbsolutePath,
		r.Content,
		r.IsBig,
		r.WriteTime,
		r.CreatedAt,
		r.UpdatedAt,
	}
}

// Names returns a slice of string names for all fields in RepoFile.
func (r repoFileDbRegistry) Names() []string {
	return []string{
		"RepoFileId",
		"RelativePath",
		"AbsolutePath",
		"Content",
		"IsBig",
		"WriteTime",
		"CreatedAt",
		"UpdatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in RepoFile.
func (r repoFileDbRegistry) IsEnum(target RepoFileFieldType) bool {
	return repoFileValidMap[target]
}

// IsRepoFileId checks whether the target object is RepoFileId.
func (r repoFileDbRegistry) IsRepoFileId(target RepoFileFieldType) bool {
	return target == r.RepoFileId
}

// IsRelativePath checks whether the target object is RelativePath.
func (r repoFileDbRegistry) IsRelativePath(target RepoFileFieldType) bool {
	return target == r.RelativePath
}

// IsAbsolutePath checks whether the target object is AbsolutePath.
func (r repoFileDbRegistry) IsAbsolutePath(target RepoFileFieldType) bool {
	return target == r.AbsolutePath
}

// IsContent checks whether the target object is Content.
func (r repoFileDbRegistry) IsContent(target RepoFileFieldType) bool {
	return target == r.Content
}

// IsIsBig checks whether the target object is IsBig.
func (r repoFileDbRegistry) IsIsBig(target RepoFileFieldType) bool {
	return target == r.IsBig
}

// IsWriteTime checks whether the target object is WriteTime.
func (r repoFileDbRegistry) IsWriteTime(target RepoFileFieldType) bool {
	return target == r.WriteTime
}

// IsCreatedAt checks whether the target object is CreatedAt.
func (r repoFileDbRegistry) IsCreatedAt(target RepoFileFieldType) bool {
	return target == r.CreatedAt
}

// IsUpdatedAt checks whether the target object is UpdatedAt.
func (r repoFileDbRegistry) IsUpdatedAt(target RepoFileFieldType) bool {
	return target == r.UpdatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r repoFileDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}

	return string(b), nil
}

// RepoFileDb provides scoped access to field enums: RepoFileDb.<Field>.
var RepoFileDb = repoFileDbRegistry{
	RepoFileId:   "RepoFileId",
	RelativePath: "RelativePath",
	AbsolutePath: "AbsolutePath",
	Content:      "Content",
	IsBig:        "IsBig",
	WriteTime:    "WriteTime",
	CreatedAt:    "CreatedAt",
	UpdatedAt:    "UpdatedAt",
}

// repoFileValidMap provides O(1) map validation for field enums.
var repoFileValidMap = map[RepoFileFieldType]bool{
	RepoFileDb.RepoFileId:   true,
	RepoFileDb.RelativePath: true,
	RepoFileDb.AbsolutePath: true,
	RepoFileDb.Content:      true,
	RepoFileDb.IsBig:        true,
	RepoFileDb.WriteTime:    true,
	RepoFileDb.CreatedAt:    true,
	RepoFileDb.UpdatedAt:    true,
}

// RepoFileField is an alias to RepoFileDb.
var RepoFileField = RepoFileDb
