// Code generated by gitmap db generate. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"

	"github.com/alimtvnetwork/gitmap-v28/cli/apperror"
)

// SearchCacheFieldType represents column name enums for SearchCache.
type SearchCacheFieldType string

// Name returns the identifier name of the field enum.
func (e SearchCacheFieldType) Name() string {
	return string(e)
}

// String returns the string representation of the field enum.
func (e SearchCacheFieldType) String() string {
	return string(e)
}

// Value returns the raw string value of the field enum.
func (e SearchCacheFieldType) Value() string {
	return string(e)
}

// IsCompare checks equality against another field enum object.
func (e SearchCacheFieldType) IsCompare(target SearchCacheFieldType) bool {
	return e == target
}

// IsEnum checks whether this field enum exists in the valid enum map.
func (e SearchCacheFieldType) IsEnum() bool {
	return searchCacheValidMap[e]
}

// MarshalJSON implements json.Marshaler.
func (e SearchCacheFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler with strict map validation.
func (e *SearchCacheFieldType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	target := SearchCacheFieldType(s)
	if !searchCacheValidMap[target] {
		return fmt.Errorf("invalid %s enum: %s", "SearchCacheFieldType", s)
	}

	*e = target

	return nil
}

// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.
func (e SearchCacheFieldType) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(string(e))
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize field to json")
	}

	return string(b), nil
}

// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.
func (e *SearchCacheFieldType) FromJSON(s string) *apperror.AppError {
	var str string
	if err := json.Unmarshal([]byte(s), &str); err != nil {
		return apperror.WrapSimple(err, "deserialize field from json")
	}

	target := SearchCacheFieldType(str)
	if !searchCacheValidMap[target] {
		return apperror.WrapSimple(fmt.Errorf("invalid %s enum: %s", "SearchCacheFieldType", str), "validate field enum from json")
	}

	*e = target

	return nil
}

// IsSearchCacheId checks whether this field enum instance is SearchCacheId.
func (e SearchCacheFieldType) IsSearchCacheId() bool {
	return e == SearchCacheDb.SearchCacheId
}

// IsQuery checks whether this field enum instance is Query.
func (e SearchCacheFieldType) IsQuery() bool {
	return e == SearchCacheDb.Query
}

// IsHits checks whether this field enum instance is Hits.
func (e SearchCacheFieldType) IsHits() bool {
	return e == SearchCacheDb.Hits
}

// IsResultJson checks whether this field enum instance is ResultJson.
func (e SearchCacheFieldType) IsResultJson() bool {
	return e == SearchCacheDb.ResultJson
}

// IsCreatedAt checks whether this field enum instance is CreatedAt.
func (e SearchCacheFieldType) IsCreatedAt() bool {
	return e == SearchCacheDb.CreatedAt
}

// IsUpdatedAt checks whether this field enum instance is UpdatedAt.
func (e SearchCacheFieldType) IsUpdatedAt() bool {
	return e == SearchCacheDb.UpdatedAt
}

type searchCacheDbRegistry struct {
	SearchCacheId SearchCacheFieldType
	Query         SearchCacheFieldType
	Hits          SearchCacheFieldType
	ResultJson    SearchCacheFieldType
	CreatedAt     SearchCacheFieldType
	UpdatedAt     SearchCacheFieldType
}

// All returns a slice of all field enums in SearchCache.
func (r searchCacheDbRegistry) All() []SearchCacheFieldType {
	return []SearchCacheFieldType{
		r.SearchCacheId,
		r.Query,
		r.Hits,
		r.ResultJson,
		r.CreatedAt,
		r.UpdatedAt,
	}
}

// Names returns a slice of string names for all fields in SearchCache.
func (r searchCacheDbRegistry) Names() []string {
	return []string{
		"SearchCacheId",
		"Query",
		"Hits",
		"ResultJson",
		"CreatedAt",
		"UpdatedAt",
	}
}

// IsEnum checks whether the target object matches any registered field enum in SearchCache.
func (r searchCacheDbRegistry) IsEnum(target SearchCacheFieldType) bool {
	return searchCacheValidMap[target]
}

// IsSearchCacheId checks whether the target object is SearchCacheId.
func (r searchCacheDbRegistry) IsSearchCacheId(target SearchCacheFieldType) bool {
	return target == r.SearchCacheId
}

// IsQuery checks whether the target object is Query.
func (r searchCacheDbRegistry) IsQuery(target SearchCacheFieldType) bool {
	return target == r.Query
}

// IsHits checks whether the target object is Hits.
func (r searchCacheDbRegistry) IsHits(target SearchCacheFieldType) bool {
	return target == r.Hits
}

// IsResultJson checks whether the target object is ResultJson.
func (r searchCacheDbRegistry) IsResultJson(target SearchCacheFieldType) bool {
	return target == r.ResultJson
}

// IsCreatedAt checks whether the target object is CreatedAt.
func (r searchCacheDbRegistry) IsCreatedAt(target SearchCacheFieldType) bool {
	return target == r.CreatedAt
}

// IsUpdatedAt checks whether the target object is UpdatedAt.
func (r searchCacheDbRegistry) IsUpdatedAt(target SearchCacheFieldType) bool {
	return target == r.UpdatedAt
}

// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.
func (r searchCacheDbRegistry) ToJSON() (string, *apperror.AppError) {
	b, err := json.Marshal(r)
	if err != nil {
		return "", apperror.WrapSimple(err, "serialize registry to json")
	}

	return string(b), nil
}

// SearchCacheDb provides scoped access to field enums: SearchCacheDb.<Field>.
var SearchCacheDb = searchCacheDbRegistry{
	SearchCacheId: "SearchCacheId",
	Query:         "Query",
	Hits:          "Hits",
	ResultJson:    "ResultJson",
	CreatedAt:     "CreatedAt",
	UpdatedAt:     "UpdatedAt",
}

// searchCacheValidMap provides O(1) map validation for field enums.
var searchCacheValidMap = map[SearchCacheFieldType]bool{
	SearchCacheDb.SearchCacheId: true,
	SearchCacheDb.Query:         true,
	SearchCacheDb.Hits:          true,
	SearchCacheDb.ResultJson:    true,
	SearchCacheDb.CreatedAt:     true,
	SearchCacheDb.UpdatedAt:     true,
}

// SearchCacheField is an alias to SearchCacheDb.
var SearchCacheField = SearchCacheDb
