package cmdautomation

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"

	"github.com/alimtvnetwork/gitmap-v28/cli/apperror"
	"github.com/alimtvnetwork/gitmap-v28/cli/result"
)

// RunDbGenerate inspects SQLite tables and generates Go/TS code artifacts.
func RunDbGenerate(opts DbGenerateOptions) DbGenerateResultMonad {
	start := time.Now()
	dbPath := opts.DbPath
	if dbPath == "" {
		dbPath = GetAutomationDbPath()
	}
	tables, errApp := inspectDbTables(dbPath)
	if errApp != nil {
		return result.Fail[DbGenerateResult](errApp)
	}
	res := processTableGeneration(tables, opts)
	res.Duration = time.Since(start)
	res.IsDryRun = opts.IsDryRun
	res.IsSuccess = true
	return result.Ok(res)
}

func inspectDbTables(dbPath string) ([]TableSchemaInfo, *apperror.AppError) {
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, apperror.WrapSimple(err, "open sqlite database for code generation")
	}
	defer db.Close()
	query := `SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_migrations';`
	rows, err := db.Query(query)
	if err != nil {
		return nil, apperror.WrapSimple(err, "query sqlite tables")
	}
	defer rows.Close()
	return scanTablesMetadata(db, rows)
}

func scanTablesMetadata(db *sql.DB, rows *sql.Rows) ([]TableSchemaInfo, *apperror.AppError) {
	var tables []TableSchemaInfo
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			continue
		}
		cols, errApp := readTableColumns(db, name)
		if errApp != nil {
			return nil, errApp
		}
		tables = append(tables, TableSchemaInfo{Name: name, Columns: cols})
	}
	return tables, nil
}

func readTableColumns(db *sql.DB, tableName string) ([]TableColumnInfo, *apperror.AppError) {
	query := fmt.Sprintf(`PRAGMA table_info("%s");`, tableName)
	rows, err := db.Query(query)
	if err != nil {
		return nil, apperror.WrapSimple(err, "query pragma table_info")
	}
	defer rows.Close()
	var cols []TableColumnInfo
	for rows.Next() {
		var col TableColumnInfo
		var notNull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&col.Cid, &col.Name, &col.Type, &notNull, &dflt, &pk); err != nil {
			continue
		}
		col.IsNotNull = notNull == 1
		col.IsPk = pk == 1
		if dflt.Valid {
			col.DfltValue = dflt.String
		}
		cols = append(cols, col)
	}
	return cols, nil
}

func processTableGeneration(tables []TableSchemaInfo, opts DbGenerateOptions) DbGenerateResult {
	var res DbGenerateResult
	res.TableCount = len(tables)
	lang := strings.ToLower(opts.Lang)
	for _, t := range tables {
		if lang == "go" || lang == "all" || lang == "" {
			appendGeneratedFile(&res, emitGoArtifacts(t, opts, &res))
		}
		if lang == "ts" || lang == "all" {
			appendGeneratedFile(&res, emitTsArtifacts(t, opts, &res))
		}
	}
	return res
}

func appendGeneratedFile(res *DbGenerateResult, file string) {
	if file != "" {
		res.GeneratedFiles = append(res.GeneratedFiles, file)
	}
}

func emitGoArtifacts(t TableSchemaInfo, opts DbGenerateOptions, res *DbGenerateResult) string {
	res.StructCount++
	res.EnumCount++
	code := generateGoStructAndEnums(t)
	if opts.IsDryRun || opts.OutDir == "" {
		return fmt.Sprintf("go:%s", t.Name)
	}
	fileName := filepath.Join(opts.OutDir, strings.ToLower(t.Name)+".go")
	_ = writeGeneratedCode(fileName, code)
	return fileName
}

func emitTsArtifacts(t TableSchemaInfo, opts DbGenerateOptions, res *DbGenerateResult) string {
	code := generateTsInterface(t)
	if opts.IsDryRun || opts.OutDir == "" {
		return fmt.Sprintf("ts:%s", t.Name)
	}
	fileName := filepath.Join(opts.OutDir, strings.ToLower(t.Name)+".ts")
	_ = writeGeneratedCode(fileName, code)
	return fileName
}

func generateGoStructAndEnums(info TableSchemaInfo) string {
	pascal := toPascalCase(info.Name)
	var b strings.Builder
	b.WriteString("// Code generated by gitmap aum db-generate. DO NOT EDIT.\n\npackage models\n\n")
	b.WriteString(fmt.Sprintf("type %s struct {\n", pascal))
	for _, c := range info.Columns {
		fName := toPascalCase(c.Name)
		gType := mapSqliteToGoType(c.Type)
		b.WriteString(fmt.Sprintf("\t%s %s `db:\"%s\" json:\"%s\"`\n", fName, gType, c.Name, toCamelCase(c.Name)))
	}
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("type %sFieldType string\n\nconst (\n", pascal))
	for _, c := range info.Columns {
		fName := toPascalCase(c.Name)
		b.WriteString(fmt.Sprintf("\t%sField%s %sFieldType = \"%s\"\n", pascal, fName, pascal, c.Name))
	}
	b.WriteString(")\n")
	return b.String()
}

func generateTsInterface(info TableSchemaInfo) string {
	pascal := toPascalCase(info.Name)
	var b strings.Builder
	b.WriteString("// Code generated by gitmap aum db-generate. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("export interface %s {\n", pascal))
	for _, c := range info.Columns {
		tsType := mapSqliteToTsType(c.Type)
		b.WriteString(fmt.Sprintf("  %s: %s;\n", toCamelCase(c.Name), tsType))
	}
	b.WriteString("}\n")
	return b.String()
}

func mapSqliteToGoType(sqlType string) string {
	upper := strings.ToUpper(sqlType)
	if strings.Contains(upper, "INT") {
		return "int64"
	}
	if strings.Contains(upper, "TEXT") || strings.Contains(upper, "CHAR") {
		return "string"
	}
	if strings.Contains(upper, "REAL") || strings.Contains(upper, "FLOA") || strings.Contains(upper, "DOUB") {
		return "float64"
	}
	if strings.Contains(upper, "BLOB") {
		return "[]byte"
	}
	if strings.Contains(upper, "BOOL") {
		return "bool"
	}
	return "string"
}

func mapSqliteToTsType(sqlType string) string {
	upper := strings.ToUpper(sqlType)
	if strings.Contains(upper, "INT") || strings.Contains(upper, "REAL") || strings.Contains(upper, "FLOA") {
		return "number"
	}
	if strings.Contains(upper, "BOOL") {
		return "boolean"
	}
	if strings.Contains(upper, "BLOB") {
		return "Uint8Array"
	}
	return "string"
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}

func toCamelCase(s string) string {
	p := toPascalCase(s)
	if len(p) == 0 {
		return ""
	}
	runes := []rune(p)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func writeGeneratedCode(path, content string) *apperror.AppError {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return apperror.WrapSimple(err, "create directory for generated code")
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return apperror.WrapSimple(err, "write generated code file")
	}
	return nil
}
